### ISSUE TITLE
Export browse-select file dialog prompts an error on MacOSX

### ISSUE THREAD

**Issue by mikucionisaau** [UPPAALModelChecker/UPPAAL-Meta#1]
The issue on MacOSX (not reproducible on Linux)

**Steps to reproduce:**

1. in the menu choose "Template export" -- export dialog pops up
2. select extension JPG
3. click Browse -- a native select file dialog pops up
4. choose some directory (e.g. Documents) and click Save

**Result:**
Error popup "The file name must have a valid file extension"

**Expected:**
The export dialog has filled with the path

**Details**
MacOSX Catalina 10.15.7
Oracle Java 8

**Comment by RasmusRendal** [comment]
The export dialog does not seem to have JPGs any more

**Comment by mikucionisaau** [comment]
Fix released with Stratego-10
