### ISSUE TITLE
UPPAAL reports: Problem in getDeclaredRange(). Please report this.

### ISSUE THREAD

**Issue by lwrage** [UPPAALModelChecker/UPPAAL-Meta#107]
**Describe the bug**
I have a model system for which I get the error message "Problem in getDeclaredRange(). Please report this." when  UPPAAL loads it or when I press F7 in the editor.

**To Reproduce**
1. Download the attached file [bug1.xml.txt](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/8681151/bug1.xml.txt) and rename it to bug1.xml
2. Open the file in UPPAAL via File > Open System
3. See error

When replacing the return statement in XX/declaration as shown below the error goes away.
```
bool p() {
  const c_id cid = t[id];
  const ix i = h[cid].o;
  const bool m = h[cid].im;

//  return m imply im[i];
//  error disappears when replacing
//  the previous line with the following two lines
  const bool active = im[i];
  return m imply active;
}
```

**Version(s) of UPPAAL tested**
Error observed in 4.1.26 and 4.1.26-1.

**Desktop (please complete the following information):**
 - Version 4.1.26-1
 - OS, Java version: Kubuntu 21.10, Java 17.0.3

**Comment by RasmusRendal** [comment]
This issue is fixed in UPPAAL Stratego 9, which can be downloaded on the [releases page](https://uppaal.org/downloads/)
