### ISSUE TITLE
Server and socketserver script uses system `env`

### ISSUE THREAD

**Issue by RasmusRendal** [UPPAALModelChecker/UPPAAL-Meta#110]
The server and socketserver script uses the `env` binary provided by the system, and afterwards `bash`. This is a problem when running the socketserver, since the socketserver's environment uses a builtin glibc and ld that may not be compatible with the users bash and env binaries.

The current workaround is using `socat` instead of the socketserver: `socat TCP-LISTEN:2350,reuseaddr,fork EXEC:"./server"`

Issue originally from here: https://github.com/UPPAALModelChecker/UPPAAL-Meta/discussions/109

**Comment by mikucionisaau** [comment]
The fixed released with Stratego-10.
