### ISSUE TITLE
[Stratego 10] Safety synthesis fails for the newspaper example

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#113]
**Describe the bug**
Since Stratego 10, synthesis of a safe strategy for Kim in the newspaper example is failing in the sense that the strategy does not verify to be safe.

See screenshot below with the query outcomes and the expected results.

![Screenshot 2022-05-24 at 11 46 17](https://user-images.githubusercontent.com/36483423/170006790-6d0926ca-7290-454e-94c7-ddfa0990b7af.png)

As a side effect, I also noticed that synthesis took much longer (68 seconds) than expected (within seconds).

**To Reproduce**
1. Open `demo/stratego/newspaper.xml`.
2. Go to verifier tab.
3. Synthesize the strategy `Travel`.
4. Verify with the next query that this is not a safe strategy.

**Expected behavior**
Safety synthesis should synthesize a safe strategy.

**Version(s) of UPPAAL tested**
Fails for Stratego 10 beta 2 and Stratego 10 beta 4.
Works for Stratego 9.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-10-beta4 (rev. 62F118AFC3403C65), May 2022
 - OS, Java version: Linux and MacOS (I am not able to check Windows)

**Additional context**
In #84 the problem was broadcasting channels. The newspaper example does not use any synchronizing channels.

**Comment by RasmusRendal** [comment]
The issue was introduced in the commit that fixed https://github.com/UPPAALModelChecker/UPPAAL-Meta/issues/93. It seems that using difference extrapolation makes the strategy correct, but it is still unacceptably slow.

**Comment by mikucionisaau** [comment]
The fix has been released with Stratego-10
