### ISSUE TITLE
double/clock in struct

### ISSUE THREAD

**Issue by davidebasile** [UPPAALModelChecker/UPPAAL-Meta#12]
Dear all, 
the official documentation at

https://www.it.uu.se/research/group/darts/uppaal/help.php?file=System_Descriptions/Declarations.shtml

also provides this example

==================
The following declares a record type S containing an integer a, a boolean b and a clock c:

typedef struct 
{ 
  int a;   
  bool b;
  clock c;
} S;
==================

however, such struct results in an error "Invalid type in structure" in Uppaal.

Best
Davide

**Comment by mikucionisaau** [comment]
Unfortunately the clock support in `struct`s never got implemented.
I traced this documentation change back to the old bug report here:
https://bugsy.grid.aau.dk/bugzilla/show_bug.cgi?id=149
So for now this is documentation issue and a feature request.

**Comment by yrke** [comment]
Hi David

Thanks for letteting us know about the issue. As Marius noted above currently double and clocks are not supported a struct members. I have updated the documentation https://docs.uppaal.org/language-reference/system-description/declarations/.

If you an interesting use case for clocks in stucts, please let us know by opening a new issue with the feature request. We use that to prioritize new features. 

If you have any further questions please feel free to reopen the issue.

Regards, Kenneth, 
UPPAAL Team
