### ISSUE TITLE
Channel array elements not supported as template parameters

### ISSUE THREAD

**Issue by pacalet** [UPPAALModelChecker/UPPAAL-Meta#123]
**Describe the bug**
A template with a channel parameter (`chan &c`) cannot be instantiated with the channel parameter bound to a channel array element (`c[0]`). The syntax error is `/System: Incomplete initialiser`.

**To Reproduce**
Download the [attached model](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/9298333/bug.txt)
 name it, e.g. `bug.xml`, load it in UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022, and check syntax.

**Expected behavior**
Channel array elements shall be accepted as template parameters or the documentation shall clearly state that this is not supported and the error message shall be informative.

**Version(s) of UPPAAL tested**
UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022
 - OS, Java version: macOS 12.5 (Monterey)

```
$ java --version
java 14.0.1 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```

**Comment by mikucionisaau** [comment]
uppaal-4.1.26 is not affected, but Stratego is, which is strange.
Textual representation of the relevant model parts is the following:
```
chan e[2];
process p(chan &c1, chan &c2) { ... }
q = p(e[0], e[1]);
system q;
```
So somehow, Uppaal Stratego thinks that `q` still has some unfilled arguments.
