### ISSUE TITLE
Inconsistent keyboard shortcuts in UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022 under macOS 12.5 (Monterey)

### ISSUE THREAD

**Issue by pacalet** [UPPAALModelChecker/UPPAAL-Meta#124]
**Describe the bug**
Under macOS 12.5 (Monterey) the keyboard shortcuts of UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022 look inconsistent.

**Describe the bug**
The copy, paste, cut... shortcuts are <kbd>ctrl</kbd> + <kbd>C</kbd> (<kbd>ctrl</kbd> + <kbd>V</kbd>, <kbd>ctrl</kbd> + <kbd>X</kbd>) in the declarations editor and in the system declarations editor, but they are <kbd>command</kbd> + <kbd>C</kbd> (<kbd>command</kbd> + <kbd>V</kbd>, <kbd>command</kbd> + <kbd>X</kbd>) in the other editors (e.g., comments, guards, synchronizations...)

Moreover, in the declarations editor and in the system declarations editor, the undo and redo shortcuts are <kbd>command</kbd> + <kbd>Z</kbd> and <kbd>shift</kbd> + <kbd>command</kbd> + <kbd>Z</kbd>; in the other editors there are no keyboard shortcuts for undo and redo.

**To Reproduce**
Create a new system in UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022, under macOS 12.5 (Monterey), try to copy/paste/cut/undo/redo in various contexts using <kbd>ctrl</kbd> or <kbd>command</kbd>.

**Expected behavior**
The keyboard shortcuts shall be consistent and shall preferably obey the macOS habits (<kbd>command</kbd> instead of <kbd>ctrl</kbd>). In the editors where they are missing undo and redo shall also have associated keyboard shortcuts.

**Version(s) of UPPAAL tested**
UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022
 - OS, Java version: macOS 12.5 (Monterey)

```
$ java --version
java 14.0.1 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```

**Comment by magoorden** [comment]
I can replicate this inconsistent behavior on my MacBook as well. And it is also present in Stratego 10 beta 6 (latest beta I have on my MacBook).

**Comment by yrke** [comment]
@loevendallund will you look at this, should be a simple task to swap usage to hardcoded ctrl to os dependent shortcut key
