### ISSUE TITLE
The window to enter license key does not close automatically when license is accepted

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#127]
**Describe the bug**
With the new beta release, a license key needs to be inserted. After inserting the key, a new pop-up window shows that the license is successfully installed (see image below). When I subsequently click on `OK` to dismiss the window, the original license pop-up window (the top one below) remains open. This feels counter-intuitive, as I need to click `Cancel` to dismiss that window.
 
![Screenshot 2022-08-24 at 15 34 06](https://user-images.githubusercontent.com/36483423/186432832-23a33af4-efc7-44ae-89a7-549ea220f0dd.png)

**To Reproduce**
1. Install a new copy of Stratego 10 beta 10.
2. Open an example model and try to run a query.
3. Notice that a license pop-up window opens.
4. Enter a correct license and click `OK`.
5. Dismiss the new pop-up window by clicking `OK`.
6. Now you are back at the window to enter your license key (which you just did).

**Expected behavior**
The original pop-up window to enter the license key should be closed automatically when the "successfully installed" window is dismissed.

**Version(s) of UPPAAL tested**
Uppaal Stratego 10 beta 10.

**Desktop (please complete the following information):**
 - UPPAAL 4.1.20-stratego-10-beta10 (rev. 812FB0F3D3DAA4DF), August 2022
 - OS, Java version: Ubuntu and MacOs (application version of Stratego)

**Comment by mikucionisaau** [comment]
Fixed in Stratego-10 beta-12
