### ISSUE TITLE
license key is no needed

### ISSUE THREAD

**Issue by EstherHKim** [UPPAALModelChecker/UPPAAL-Meta#129]
**Describe the bug**
To be honest, I am not sure it is bug or not. But I have not told that Windows OS is free from license key. Therefore I am reporting this. A license key has not been required when I first started the program. 

**To Reproduce**
1. Download the zip file and uninstall it. 
2. Open a Stratego 10 beta 10.
3. Expected popup for licence request, but does not exist.  

**Expected behavior**
I Expected popup for licence request, but does not exist.  

**Version(s) of UPPAAL tested**
UPPAAL Stratego 10 beta 10.

**Screenshots**

**Desktop (please complete the following information):**
 - Version: UPPAAL 4.1.20-stratego-10-beta10
 - OS, Java version: Windows 10 64bit, Java 11

**Additional context**

**Comment by mikucionisaau** [comment]
@EstherHKim What do you get when you switch to `Simulator` or `Verifier` tabs? Reload (press `F5`)?
The GUI should allow one to open and edit documents without requiring license key, it's only simulation and verification functionality requires that.

**Comment by EstherHKim** [comment]
@mikucionisaau I will check and update what will happen when I try Simulator or Verifier taps. When I open example model, UPPAAL Stratego request license key and I guess it will valid for 72 hours. I will try again when license key is initiated.

**Comment by mikucionisaau** [comment]
@EstherHKim please check Stratego-10 beta-12

**Comment by EstherHKim** [comment]
I checked both Windows version and Linux version. I can see the problem "delete function" that I reported before has been solved. Thank you! :)

**Comment by mikucionisaau** [comment]
Fixed in Stratego-10 beta-12
Thank you!
