### ISSUE TITLE
delete tap is not working 

### ISSUE THREAD

**Issue by EstherHKim** [UPPAALModelChecker/UPPAAL-Meta#130]
**Describe the bug**
When I tried to delete the location, edge and nail of model, mouse tapping is not working. But delete using keyboard is working. 

**To Reproduce**
1. Make two locations. 
2. Make an edge between those two locations. 
3. Try to do 1)mouse right-click 2)delete   

**Expected behavior**
The delete function using mouse is expected to be worked. 

**Version(s) of UPPAAL tested**
UPPAAL Stratego 10 beta 10

**Screenshots**
![stratego_delete](https://user-images.githubusercontent.com/89918210/186599293-0e89e7bb-3671-4dbd-9acb-919f3c4d5961.png)
![stratego_delete edge](https://user-images.githubusercontent.com/89918210/186599303-0f7360fc-198c-4e45-aa39-a3cdee998e99.png)

**Desktop (please complete the following information):**
 - Version: 4.1.20-stratego-10-beta 10
 - OS, Java version: Windows 10 64bit, Java 11

**Additional context**

**Comment by mikucionisaau** [comment]
@EstherHKim please check if this is fixed in Stratego-10 beta-12

**Comment by mikucionisaau** [comment]
Fixed in Stratego-10 beta-12
