### ISSUE TITLE
Deleting "branch point". 

### ISSUE THREAD

**Issue by EstherHKim** [UPPAALModelChecker/UPPAAL-Meta#133]
**Describe the bug**
I have add branch point between 2 state location and found out there is no scroll bar I can use for deleting the branch point. I also checked stratego version 9 and it also don't has the bar. Therefore, it looks like it is not only this beta version's problem. But for the case if it is not intended, I am reporting it.     

**To Reproduce**
1. Go to 'Empty Template'
2. Add two random state. 
3. Add "branch point" between those states. 
4. Try to delete it. (I can delete it with keyboard though) 

**Expected behavior**
When I click the right butten on the branch point, I expect some scroll down just as I done the same thing on the state location. 

**Version(s) of UPPAAL tested**
UPPAAL 4.1.20-stratego-10-beta12

**Screenshots**
![error_branch point delete](https://user-images.githubusercontent.com/89918210/188818370-fedd9bf2-c3d8-4d0f-8809-d907f0a128ae.png)

**Desktop (please complete the following information):**
- UPPAAL 4.1.20-stratego-10-beta12
 - Linux 20.04 (with Java 11.0.16) and Windows 10 (Java 11.0.12) 

**Additional context**

**Comment by yrke** [comment]
Issue is closed in Stratego-10 beta-13
