### ISSUE TITLE
copy and paste is not available 

### ISSUE THREAD

**Issue by EstherHKim** [UPPAALModelChecker/UPPAAL-Meta#134]
**Describe the bug**
I tried to copy and paste part of the code but it seems like it doesn't work. I tried same thing with stratego9 on same version OS and can see it works there.  

**To Reproduce**
1. Go to 'Declarations' of any template.
2. Set a block of part of a code.
3. Press 'ctrl + c' 
4. Press 'ctrl + p'

**Expected behavior**
I expected the part I copied to be pasted to place where I want to put. 

**Version(s) of UPPAAL tested**
UPPAAL 4.1.20-stratego-10-beta12

**Screenshots**
![uppaal_copy](https://user-images.githubusercontent.com/89918210/189338196-e001466a-bd91-4f2f-8a62-e7c7b12cb8f6.png)

**Desktop (please complete the following information):**
 - Version [UPPAAL 4.1.20-stratego-10-beta12]
 - OS, Java version: [Linux 20.04, Java11]

**Additional context**

**Comment by thorulf4** [comment]
`ctrl + p` is not a shortcut we support, we use `ctrl + c` and `ctrl + v` for copy and paste respectively.

We were also unable reproduce pasting with `ctrl + p` on stratego9

**Comment by EstherHKim** [comment]
Oh, it was typo. I mean ctrl + v instead of ctrl p. I am sorry for my typo.

**Comment by thorulf4** [comment]
This will be fixed in stratego10
