### ISSUE TITLE
[MacOS] Use relative instead of absolute file name suggestion in Save System As window

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#137]
**Describe the bug**
When you select 'Save System As' in Uppaal, the MacOS native window opens as shown below in the screenshot.

![Screenshot 2022-09-15 at 15 00 28](https://user-images.githubusercontent.com/36483423/190410193-1316aa47-1d16-48b4-9af2-f301bbc24835.png)

As you can see, an absolute file name is suggested as default at 'Save As:'. If a user chooses another folder, the absolute file name does not change. Therefore, the actual file name will be this `path/to/chosen/folder/<suggested absolute path>`. 

I see that other applications on MacOS only suggest a relative file name for 'Save As:', thus making switching between folders easy without changing the suggested file name.

**To Reproduce**
1. Open a model, for example one of the examples.
2. Click on File -> Save System As.
3. Observe the suggested absolute path file name.
4. Select another folder than the suggested one (e.g., switch from Documents to Desktop).
5. Click Save without changing the file name.
6. Observe that the new file has the suggested absolute file path as it's file name.

**Expected behavior**
A relative file name should be suggested for 'Save As:', like `cruise.xml`.

**Version(s) of UPPAAL tested**
UPPAAL Stratego 10 beta 13.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-10-beta13 (rev. 772014A1367888DD), September 2022
 - OS, Java version: MacOS 12.6

**Comment by mikucionisaau** [comment]
The same issue as #135 but in a different context

**Comment by magoorden** [comment]
> The same issue as #135 but in a different context

I would not call it the same issue. If you would manually remove the absolute path from the dialog in #135, Uppaal still complains about using the wrong extension (and thus not exporting it).

With Save As the model is still saved, but it has the absolute path in the new file name.
