### ISSUE TITLE
[MacOS] Application logo not picked up in the dock

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#138]
**Describe the bug**
UPPAAL Stratego's application logo is not displayed in the dock on MacOS. It shows the generic Java logo.

![Screenshot 2022-09-15 at 15 11 26](https://user-images.githubusercontent.com/36483423/190412842-4ac3e6f1-1ddf-4ad7-ad24-4c4b863e93f0.png)

Yet, the correct logo is displayed in Finder when I'm in the Application folder.

![Screenshot 2022-09-15 at 15 11 20](https://user-images.githubusercontent.com/36483423/190412996-aa616a46-d9d9-46cc-a070-f38be9b957f5.png)

**To Reproduce**
1. Go to the Applications and find UPPAAL.
2. Observe the logo in front of the application.
3. Open UPPAAL.
4. See that the generic java logo is shown in the dock.

**Expected behavior**
The same logo as in the Finder should also be shown on the dock when the application is open.

**Version(s) of UPPAAL tested**
UPPAAL Stratego 10 beta 13.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-10-beta13 (rev. 772014A1367888DD), September 2022
 - OS, Java version: MacOS 12.6

**Additional context**
Also switching between applications using `Cmd + tab` shows the generic java logo (it probably copies the same logo as in the dock).

**Comment by mikucionisaau** [comment]
OK, it seems that Java has finally an API for that:
https://stackoverflow.com/a/56924202/2685239

**Comment by thorulf4** [comment]
This will be fixed in stratego10
