### ISSUE TITLE
[MacOS] Some keyboard shortcuts are inconsistent

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#139]
**Describe the bug**
Some keyboard shortcuts are inconsistent with what's common with other MacOS applications and inconsistent with the Windows/Linux version of UPPAAL.

Below are the ones I already discovered. I don't know if there are more keyboard shortcuts that need attention.

- Find; now: `ctrl + f`; expected: `cmd + f` 
- Find globally; now: `ctrl + shift + f`; expected: `cmd + shift + f` 
- Replace; now: `ctrl + r`; expected: `cmd + r` 
- Replace globally; now: `ctrl + shift + r`; expected: `cmd + shift + r` 
- Refresh engine; now: `cmd + r`; expected: `F5` 
- Check syntax; now: `cmd + e`; expected: `F7` 
- Zoom in; now: `ctrl + +`; expected: `cmd + +` 
- Zoom out; now: `ctrl + -`; expected: `cmd + -` 
- Zoom to fit; now: `ctrl + *`; expected: `cmd + *` 
- Zoom 100%; now: `ctrl + /`; expected: `cmd + /` 

**Version(s) of UPPAAL tested**
UPPAAL Stratego 10 beta 13.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-10-beta13 (rev. 772014A1367888DD), September 2022
 - OS, Java version: MacOS 12.6

**Comment by mikucionisaau** [comment]
All of the key strokes have been addressed in Stratego-10, except `F7`.
