### ISSUE TITLE
[MacOS] Preference settings in the 'wrong' menu

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#142]
**Describe the bug**
On MacOS, application preferences are normally located under the application name in the Menu Bar. For UPPAAL, they are located under Edit. This might confuse MacOS users when they are looking for the preferences.

![Screenshot 2022-09-16 at 09 16 02](https://user-images.githubusercontent.com/36483423/190579252-4ee9fba5-a149-4e4f-afed-946b4fddb8a0.png)

**Expected behavior**
The preferences are located under the UPPAAL menu.

Below is an example of Outlook

![Screenshot 2022-09-16 at 09 17 57](https://user-images.githubusercontent.com/36483423/190579621-9a1531c6-6f05-4c07-828b-2ce44dbea3c8.png)

and Spotify

![Screenshot 2022-09-16 at 09 18 46](https://user-images.githubusercontent.com/36483423/190579814-ace12ce3-ed0e-46b3-8a81-2bbb87a189e7.png)

(And they seem to have the keyboard shortcut `cmd ,`)

**Version(s) of UPPAAL tested**
UPPAAL Stratego 10 beta 13.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-10-beta13 (rev. 772014A1367888DD), September 2022
 - OS, Java version: MacOS 12.6

**Comment by mikucionisaau** [comment]
@magoorden  Could you please add a screenshot with UPPAAL menu open?
This is very much Mac-specific, we probably need to do something special about it.
Also the suggestion for `cmd ,` is nice.

**Comment by magoorden** [comment]
This is how the UPPAAL menu looks like on MacOS.

![Screenshot 2022-09-20 at 10 07 28](https://user-images.githubusercontent.com/36483423/191203218-c895d542-12a9-480c-93c7-23f893bd5d06.png)
