### ISSUE TITLE
Syntax errors unreadable in dark mode

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#143]
**Describe the bug**
In dark mode (using FlatLaf Dark theme), the syntax errors are unreadable, as it is a black font on a dark gray plane.

![Screenshot 2022-09-16 at 09 22 01](https://user-images.githubusercontent.com/36483423/190580608-bd3df174-9d7b-4648-b79d-afbd59bce7c8.png)

**Expected behavior**
A lighter colored font for better contrast with the dark gray background.

**Version(s) of UPPAAL tested**
UPPAAL Stratego 10 beta 13.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-10-beta13 (rev. 772014A1367888DD), September 2022
 - OS, Java version: MacOS 12.6

**Comment by thorulf4** [comment]
This will be fixed in stratego10
