### ISSUE TITLE
Integer guard not satisfied error during simulation

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#149]
**Describe the bug**
I have a model where an edge has two select variables, but only one is actually used, see this minimum working example [MWE_integer_guard.xml.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/9685782/MWE_integer_guard.xml.zip) and the screenshot below.

![Screenshot 2022-09-30 at 17 28 51](https://user-images.githubusercontent.com/36483423/193304603-73767ec3-4bfc-460a-b50d-829585ba3754.png)

When I go to the concrete simulator tab, I see a list of possible transitions where `j` is `0` or `3` and `i` is `0` or `1`. So the modulo operator works up to this point.

Now, if I select any transition with `i=0`, the simulation works fine. But if I select a transition with a value other than `0` for `i` (in this example there is only 1 alternative, but the problem seems to scale for larger ranges of `i`), I get the following error.

![Screenshot 2022-09-30 at 17 17 25](https://user-images.githubusercontent.com/36483423/193305468-535cc942-f9d8-4b70-981b-dcaac430069f.png)

![Screenshot 2022-09-30 at 17 18 10](https://user-images.githubusercontent.com/36483423/193305489-0ff7d966-92b0-4e89-88b1-fde684fe5133.png)

I can't figure out why I get this error message. The evaluation of the guard `j%3 == 0` seems to be evaluated differently for different values of the unrelated select variable `i`.

**To Reproduce**
1. Open the supplied MWE.
2. Go to the concrete simulator tab.
3. Start a random simulation.
4. Observe that you get the above error at some point.

**Expected behavior**
No error message. Or if something is indeed wrong with the model, a more indicative error message. 

**Version(s) of UPPAAL tested**
UPPAAL Stratego 10 RC1

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-10-rc1 (rev. A19C64CD83B82AB5), September 2022
 - OS, Java version: Ubuntu 20.04.3 LTS

**Comment by mikucionisaau** [comment]
Fix included in Stratego-10
