### ISSUE TITLE
Stratego-8-beta-6: open system prompts for save changes, while setting changes already have been saved

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#15]
**Describe the bug**
In beta 6, settings are saved in the underlying xml file. When a user wants to open a new model file, Uppaal checks whether there are changes not saved before actually letting the user load a new model. When unsaved changes are detected, the user is asked whether these changes needs to be saved or not. Unfortunately, this prompt is also shown to the user when changes in settings are already saved.

**To Reproduce**
1. Change a setting trough the Options drop-down menu, for example, set the discretization step for hybrid systems to 1 instead of the default 0.01.
2. Save the model.
3. Verify that the new setting has been saved by opening the xml view of the model (in for example a text editor) and look for the `<option/>` tag. 
4. Request Uppaal to open a system.
5. A 'Save System' prompt is now opened.

**Expected behavior**
Uppaal should recognize that the changed settings have already been saved.

**Uppaal version**
- Upaal Stratego version 8 beta 6.

**Desktop**
 - OS: Ubuntu 20.04.1 LTS.

**Additional context**
The prompt is not shown when settings are reset by pressing `Clear option overrides` and saving the model before opening another one.

**Comment by mikucionisaau** [comment]
@waefwerf , could you take a look at this report?

**Comment by mikucionisaau** [comment]
solved on the main branch

**Comment by yrke** [comment]
This issue have been fixed in the latest beta release
