### ISSUE TITLE
Stratego-8-beta-6: Non-default options in an Uppaal file are not loaded together with the model

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#16]
**Describe the bug**
In Stratego-8-beta-6, non-default options are saved together with the queries. Unfortunately, opening a model with such saved non-default settings does not import these settings into Uppaal. To be precies, this concerns the options that hold for all queries, i.e., those changed through the Options menu in the top of the GUI. Loading options goes fine when they are saved for a specific query by using the gear button next to the query field.

**To Reproduce**
1. Have a Uppaal model with non-default settings saved. This can be verified by looking for the `<option/>` tag in the xml file.
2. Open the model in Uppaal.
3. In options, the default values are shown and not the values in the model file.
4. Running queries use the values shown in the option drop-down menu and not the options saved in the model file.

I have tested this for a limited set of options (discretization step for hybrid systems, number of succesful runs, maximum number of runs, number of good runs, and number of runs to evalue).

**Expected behavior**
When a model is opened with saved settings, the option drop-down menu should reflect this and queries should used the saved option settings.

**Uppaal version**
- Uppaal Stratego 8 beta 6

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS.

**Comment by mikucionisaau** [comment]
@waefwerf , another report about options.

**Comment by RasmusRendal** [comment]
This seems to have been implemented in Stratego 9.
