### ISSUE TITLE
Error message `Error reading model.xml` too broadly formulated

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#167]
**Describe the bug**
Today I ran `verifyta model.xml` and received the following error message:

`Error reading model.xml`.

My first idea was that maybe my modeled contained something that could not be read by verifyta, for example some deprecated model or query features. After a while I realized that I forgot to include the folder in the model path. So in effect, verifyta could not read the xml-file because the supplied file did not exists.

So the error message produced by verifyta is ambiguous, as there might be multiple causes for a reading error.

**To Reproduce**
1. Run `verifyta <nonexistingmodel>.xml` with a non-existing model path.
2. Observe the error message.

**Expected behavior**
I would expect a more precise error message explaining what caused the problem with reading the xml-file. In this case, the error message would be much more helpful if it reads

`Error reading model.xml: no such file exists`.

**Version(s) of UPPAAL tested**
UPPAAL Stratego 10

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-10 (rev. 37ECAAA437FE60EE), October 2022
 - OS, Java version: Ubuntu 20.04.3 LTS

**Comment by thorulf4** [comment]
This will be fixed in the next release

**Comment by thorulf4** [comment]
This has been fixed in newly released Stratego-11 beta-4
