### ISSUE TITLE
[FlatLaf Dark] Query and Comment field become light gray when selecting multiple queries

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#168]
**Describe the bug**
When you use dark mode, i.e., `FlatLaf Dark`, and select multiple queries, the `Query` and `Comment` fields get a light gray background, which is very intrusive when you work in a dark mode. 

![Screenshot 2022-11-14 at 14 09 48](https://user-images.githubusercontent.com/36483423/201668992-43ecdbe1-73ce-45ce-be57-580cb9369289.png)

**To Reproduce**
1. Go to `Verifier` tab
2. Select multiple queries
4. See as above

**Expected behavior**
I would expect that both `Query` and `Comment` maintain there normal background when selecting multiple queries. 

**Version(s) of UPPAAL tested**
UPPAAL Stratego 10.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-10 (rev. 37ECAAA437FE60EE), October 2022
 - OS, Java version: Ubuntu 20.04.3 LTS,, macOS 12.6.1.

**Comment by mikucionisaau** [comment]
Fixed in Stratego 11 by revising the colors of all widgets.
