### ISSUE TITLE
Stratego-8-beta-6: Internal error when opening model where some specific options are saved on query level

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#17]
**Describe the bug**
In Stratego-8-beta-6, options other than the default ones can be saved for each query specific. For some of the options, opening such a model result in an internal error "Caught unexpected java.lang.RuntimeException: Could not interpret parameter field properly." At least one of the options resulting in this error is `Number of successful runs`. At least one of the options resulting in *no* error is `Discretization step for hybrid systems`. I don't exhaustively tested all options to figure out which of them result in this internal error.

**To Reproduce**
1. Have a Uppaal model without saved settings.
2. Select a query.
3. Click the gear button.
4. Go to `Learning parameters`
5. In the pop-up window, change `Number of successful runs' (the first option) to something else, for example 20 (removing the last 0). A red star should appear behind the option name.
6. Click OK. Verify that the gear button now has a small yellow circle.
7. Save the file. You might want to verify that the option has been saved by looking in the xml file for the `<option/>` tag.
8. Open another (random) Uppaal model.
9. Open the Uppaal model with the saved option.
10. Internal error appears.

**Expected behavior**
No internal error while opening the model. Expected behavior can be observed by following the steps above, but now changing the `Discretization step for hybrid systems` option.

**Uppaal version**
- Uppaal Stratego 8 beta 6.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS.

**Comment by mikucionisaau** [comment]
@waefwerf  this seems to be critical as the option settings prevent proper usage.

**Comment by yrke** [comment]
This issue have been fixed in the latest beta release
