### ISSUE TITLE
DTD errors with UPPAAL model xml

### ISSUE THREAD

**Issue by senniraf** [UPPAALModelChecker/UPPAAL-Meta#176]
**Describe the bug**
UPPAAL's produced xml model files are not consistent with the `-//Uppaal Team//DTD Flat System 1.1//EN` DTD from http://www.it.uu.se/research/group/darts/uppaal/flat-1_2.dtd

**To Reproduce**
1. Open UPPAAL
2. Create a new model and save it
3. Validate the xml model file against the dtd specified in the xml file
4. I got 2 errors when validating with the VSCode XML Extension:
```
Element type "nta" must be declared.
The content of element type "query" must match "(comment,formula)".
```

**Expected behavior**
The XML model file is valid to its specified DTD.

**Version(s) of UPPAAL tested**
UPPAAL 4.1.26-1

**Desktop (please complete the following information):**
 - Version: UPPAAL 4.1.26-1
 - OS, Java version: Linux 64-bit, openjdk 11.0.17

**Comment by mikucionisaau** [comment]
Thank you for the report.
We have fixed the `flat-1_2.dtd` online by adding the missing tags, so now the UPPAAL-4.1.26 documents validate.
