### ISSUE TITLE
Stratego-8-beta-6: Some models gives `Expected "START_OBJECT", got "EOF"` in the simulator

### ISSUE THREAD

**Issue by jakobht** [UPPAALModelChecker/UPPAAL-Meta#18]
**Describe the bug**
The simulator gives `Expected "START_OBJECT", got "EOF"` in the simulator after taking the first transition in the attached model:
[lightswitch.xml.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/5932297/lightswitch.xml.zip)

**To Reproduce**
Open the attached model, go to simulator, take the only enabled transition

**Expected behavior**
No exception

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro linux 
 - Version: Stratego-8-beta-6

**Comment by mikucionisaau** [comment]
1) bug confirmed
2) this seems to have beein fixed on the main branch, pending relesae

**Comment by yrke** [comment]
Fixed in beta-7
