### ISSUE TITLE
Concrete simulator: Random simulation only available after selecting the first transition manually

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#189]
**Describe the bug**
I have a model for which I want to run a concrete simulation automatically. But I noticed that the `Random` button is unavailable to press. It only became available for me once I selected the first transition manually.

The model to reproduce the problem with:
[IntelligentLight.xml.txt](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/10839699/IntelligentLight.xml.txt)

**To Reproduce**
1. Open the model.
2. Go to the concrete simulator tab.
3. Expand the time horizon a couple of times.
4. Notice that the `Random` button is unselectable.
5. Select the first transition manually.
6. Notice that `Random` is now clickable, and clicking results in an automatic simulation.

**Expected behavior**
A random simulation is available directly from the start.

**Version(s) of UPPAAL tested**
UPPAAL 5.0 Beta 4

**Desktop (please complete the following information):**
 - Version UPPAAL 5.0.0-beta4 (rev. 59F23580C4E5D80F), 2023-02-21
 - OS, Java version: MacOS Ventura 13.2.1 (22D68)

**Comment by thorulf4** [comment]
This issue was resolved in In Uppaal 5.0
