### ISSUE TITLE
De-/Incrementing a meta int variable yields wrong result

### ISSUE THREAD

**Issue by Brias** [UPPAALModelChecker/UPPAAL-Meta#190]
**Describe the bug**
When a `meta int` variable is used in an expression and the result is assigned to the same meta variable, the result is not as expected.

**To Reproduce**
1. Create a template with one start state and a transition from that start state to itself.
2. In the update section of this transition add `i++`
3. In the template declarations add `meta int[0,12] i = 0;`
4. When running the simulator, the error `The successors of this state are not well defined. [...]` is shown after the transition was triggered a few times but less than 12 times. 

**Expected behavior**
The meta variable holds the correct result of the expression, e.g. is increment by one when the expression is `i++`. 

**Screenshots**
![uppaal_meta](https://user-images.githubusercontent.com/6921835/221697256-afb6bee0-6328-41ba-bc67-c49160b1f1ec.png)

![uppaal_meta_declarations](https://user-images.githubusercontent.com/6921835/221697331-eb22362a-88b7-4798-8a7c-45a82a3a4296.png)

![uppaal_meta_simulator](https://user-images.githubusercontent.com/6921835/221697693-e64816e6-53fd-4bdb-ae55-4d51a605db7e.png)

**Version(s) of UPPAAL tested**
- UPPAAL 4.1.26-1 (rev. 7BCF30B7363A9518), February 2022
- UPPAAL 4.1.20-stratego-11 (rev. 323D987339A98B21), December 2022

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64, Kernel 6.1.12-arch1-1
 - Java version: openjdk 19.0.2

**Comment by mikucionisaau** [comment]
Thanks for the report.

I have added a guard `i<12` and the error does not happen. It looks like the simulator evaluates the update three times. Such behavior in the simulator is not expected, but it also should not be relied upon as the simulator may execute edges out of order, leaving the meta variables in arbitrary state.

Currently the only correct use of `meta` variables is for value passing during the synchronization (one process sets the variable and then another another reads it during the same transition).

**Comment by Brias** [comment]
Thanks for the fast reply.

If i cannot set an arbitrary int variable to meta for a template that would mean that when doing controller synthesis this variable will always be part of the decision process of which transition is controlled by the synthesized controller, right? If so, is there any other mechanism to remove that variable from the state space but keep the variable itself?

**Comment by mikucionisaau** [comment]
If the variable (state) is a part of the decision, then it has to be a part of the state (space).
Another way to avoid a variable state, is to declare it `const`, but that is probably not what you want.

**Comment by Brias** [comment]
Ok, then I need to rethink my model. Thanks for the support!
