### ISSUE TITLE
Cannot download Stratego 11

### ISSUE THREAD

**Issue by lwrage** [UPPAALModelChecker/UPPAAL-Meta#194]
**Describe the bug**
I tried to download UPPAAL Stratego 11 from https://uppaal.org/downloads/. Clicking on the Windows version loads the link https://uppaal.org/dl/uppaal-4.1.20-stratego-11-win64.zip which results in a 404 Not found error. Same result for Linux and Mac version.

**Comment by thorulf4** [comment]
Thanks for the report, the issue seems to exist for stratego 11 and 10.

In the mean time I recommend downloading Uppaal 5 pre release which have the same features as stratego 11 including some bug fixes.
https://uppaal.org/downloads/#uppaal5.0

**Comment by thorulf4** [comment]
New download links have been provided for stratego 11 and 10
