### ISSUE TITLE
Generated strategies overwrite previous strategies even if they have a different variable name

### ISSUE THREAD

**Issue by GameMonkey** [UPPAALModelChecker/UPPAAL-Meta#198]
**Describe the bug**

I synthesize 3 strategies in my model, and then I store them. However, it is the latest synthesized strategy that is stored even though they have different names.
```
strategy plan_soc = <...>
strategy plan_temp = <...>
strategy plan_both = <...>

saveStrategy("plan_soc.json", plan_soc)
saveStrategy("plan_temp.json", plan_temp)
saveStrategy("plan_both.json", plan_both)
```

**To Reproduce**

Unzip the mode: [model.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/11260758/model.zip)
To quickly synthesize the strategies, run the model using 
```
<path-to-verifyta> --max-iterations 1 --reset-no-better 1 --good-runs 1 --total-runs  1  --runs-pr-stat 1  -D 0.5 --truncation-error 0.1 --truncation-time-error 0.5  model.xml
```
The 3 json files are identical, which they cannot be as the point var vectors are different.

**Expected behavior**
3 different strategies. This is easy to verify as the 3 different point var vectors must not be the same.

**Version(s) of UPPAAL tested**
Uppaal 5 RC2

**Desktop (please complete the following information):**
 - Version UPPAAL 5.0.0-rc2 (rev. 92306F488AF675BA), March 2023
 - Linux martin 5.15.0-69-generic # 76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - openjdk 18.0.2-ea 2022-07-19

**Comment by thorulf4** [comment]
This issue was resolved in Uppaal 5 rc3
