### ISSUE TITLE
Double values in clock bounds and guards result in time-lock

### ISSUE THREAD

**Issue by GameMonkey** [UPPAALModelChecker/UPPAAL-Meta#204]
**Describe the bug**
I have a double value that I use as a bound in an invariant and as a guard. However, as soon as the model reaches that location, the system is in a time-lock.

The bound in my example is '1'. The error is not present if the bound is of type 'int'. Nonetheless, I need it to be able to be a double value.

**To Reproduce**
1. Open this zip file of a minimal example and run the simulation query:
[warehouse_bug.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/11732152/warehouse_bug.zip)
2. See error

**Expected behavior**
That the model steps to the next location when the conditions are met. 

**Version(s) of UPPAAL tested**
UPPAAL 5.0.0-rc4 (rev. 6F3B9F1B33482FBD), 2023-05-31

**Desktop (please complete the following information):**

openjdk 18.0.2-ea 2022-07-19
OpenJDK Runtime Environment (build 18.0.2-ea+9-Ubuntu-222.04)
OpenJDK 64-Bit Server VM (build 18.0.2-ea+9-Ubuntu-222.04, mixed mode, sharing)

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

Linux martin 5.15.0-73-generic # 80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thorulf4** [comment]
Hi, thank you for your bug report!
We have addressed your issue and it should be resolved in most recent release candidate i.e. Uppaal 5 rc6
