### ISSUE TITLE
"Server connection lost" when using fint()

### ISSUE THREAD

**Issue by MTrezzy** [UPPAALModelChecker/UPPAAL-Meta#23]
**Describe the bug**
When using the buildin function fint(), it is not possible to use the simulator anymore because we get the error "Server connection lost"

**To Reproduce**
1. Create a template
2. Add a transition with as update the call of the function cast()
3. In the declarations of the template define:
int x=0;
double dx=0.0;
void cast() { x = fint(dx); }
4. Do not forget to declare the system in the system declaration
5. Open the simulator tab and see the error

**Expected behavior**
When clicking the simulator tab, no error should appear and I should be able to execute my simulation.

**Desktop:**
 - OS: Ubuntu 18.04.5 LTS
 - Version Uppaal 4.1.24 (rev. 29A3ECA4E5FB0808), November 2019

**Comment by mikucionisaau** [comment]
There are two issues:
1) the symbolic simulator does not support floating point operations at all. It uses symbolic representation for clock values and cannot represent floating point values. In principle we could add floating point support within function scope, but then it may easily explode in the number of states. Moreover random number generating functions would result in a hidden non-determinism making the whole symbolic verification futile. If we were to allow any floating points in simbolic simulator, all of these operations would have to be checked and banned -- that requires careful static analysis which is undecidable in general. That is a lot of effort for little gain, hence low priority.

2) concrete simulator does not support floating point values, it simply lacks the implementation and a few widgets to be useful in ODE context. We are working on this.

So currently such code can be used only in the verifier tab in a context of SMC queries (`simulate`, `Pr[]`, etc).

**Comment by magoorden** [comment]
Maybe we should report to user what the actual problem is instead of just closing the server connection and let the user be in the dark. As I understand from @mikucionisaau answer, models containing floating points are not supported in the concrete and symbolic simulators. Imho, a message such as "Currently, a model containing floating point operations are not supported for the concrete/symbolic simulator." indicates to the user that there is no bug in Uppaal.

**Comment by nanderv** [comment]
I think the bug may be more complicated than that. The concrete simulator works fine for me when using fint directly inside the model. However, moving the fint into a custom function causes it to reliably crash the concrete simulator. 
I understand there may be UPPAAL design decisions that cause function calls to be different from using functions within the model. However, it feels very strange to me that using fint is possible in the concrete simulator if used directly in the template, and not when using it in a function call.

**Comment by mikucionisaau** [comment]
Seems to be fixed in `4.1.25-5`: at least t did not crash for me on Linux.

**Comment by mikucionisaau** [comment]
Stratego-10 reports the issue in Symbolic Simulator:
![image](https://user-images.githubusercontent.com/4868894/194230524-3ee88886-f052-4b12-9e36-f1c3786f3edc.png)

The updates like `a=fint(random(10))` are also detected and the Symbolic Simulator is disabled altogether as it does not support such expressions.
