### ISSUE TITLE
function returns constant-over-time value from regular clock expression

### ISSUE THREAD

**Issue by mikucionisaau** [UPPAALModelChecker/UPPAAL-Meta#24]
Consider declaration:
```c
clock u;
double funcu() {  return u; } 
double funcu0() { return u + 0; }
```
Then query `simulate [<=4; 1] { funcu(), funcu0() }` results in the following plot:
![image](https://user-images.githubusercontent.com/4868894/108975314-a623ee80-7686-11eb-9b0d-2b16d4704e37.png)

which shows unexpected trajectory of `funcu()`, where the expectation is that it should coinside with `funcu0`.

Tested on Uppaal-4.1.24, 

Meanwhile Uppaal Stratego 4.1.20-7 shows a different, also unexpected, plot:
![image](https://user-images.githubusercontent.com/4868894/108976042-6a3d5900-7687-11eb-8800-590d1d6d92d6.png)

Uppaal Stratego on the main branch:
![image](https://user-images.githubusercontent.com/4868894/108976155-8640fa80-7687-11eb-95ae-5a1b4313242f.png)

Reported by Ulrik Nyman.

**Comment by ulriknyman** [comment]
@petergjoel thinks that the first of the two functions returns the clock index instead of the value of the clock. It should be handled in the compile step.

**Comment by mikucionisaau** [comment]
The clock index represents a reference to a clock, thus the last step of conversion to the return type is missing.

**Comment by mikucionisaau** [comment]
Fix released with Stratego-10:
![image](https://user-images.githubusercontent.com/4868894/194231484-4f52dc10-26de-4eff-b7e3-3550d8b3b0a6.png)
