### ISSUE TITLE
Misleading popup when saving learning strategies

### ISSUE THREAD

**Issue by thorulf4** [UPPAALModelChecker/UPPAAL-Meta#247]
**Describe the bug**
When saving a strategy a misleading confirmation popup is displayed.

**To Reproduce**
1. Create any named learning strategy
2. Save this named strategy using the saveStrategy query
3. Observe the confirmation popup

**Expected behavior**
I expect the confirmation to be clear and concise informing the user the strategy was saved succesfully

**Version(s) of UPPAAL tested**
Uppaal 5.0 and forward

**Screenshots**
![image](https://github.com/UPPAALModelChecker/UPPAAL-Meta/assets/10059450/66622a3e-9cfe-4b0a-8461-9b2bec4e5867)

**Desktop (please complete the following information):**
UPPAAL 5.0.0 (rev. 714BA9DB36F49691), June 2023
Copyright (c) 2011 - 2023, Aalborg University.
Copyright (c) 1995 - 2011, Uppsala University and Aalborg University.
All rights reserved.
Compiled using -DENABLE_TIGA -DMULTI_TERMINAL -DENABLE_TIGA_SMC -DENABLE_STORE_MINGRAPH -DTIGA_OTF_BUCHI -DENABLE_LSC
Built with Boost-1.79.0, LibXml2-2.9.14, xxHash-0.8.1, UTAP-1.1.6, UUtils-1.2.0, UDBM-2.0.11, and UCDD-0.2.1
Licensed to Thorulf Neustrup / Aalborg University (cs.aau.dk).

 - Windows 11
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

**Additional context**

**Comment by mikucionisaau** [comment]
I've fixed this issue in the repo (waiting to be released).
The issue was incorrect result message being picked up (it treated as if a strategy was created rather than saved, it also depends on some flags that are meaningless in this case, hence the text may vary). 

So the strategy itself is good, it's only the message that's misleading.
