### ISSUE TITLE
Squaring by x * x and pow(x, 2) take significantly different time 

### ISSUE THREAD

**Issue by mihsamusev** [UPPAALModelChecker/UPPAAL-Meta#25]
**Describe the bug**
Squaring a variable by multiply it by itself `x * x` is much faster than using `pow(x, 2)` function.

**To Reproduce**

***Global declaration***
```c
clock Cost;
```
***Templates***
`objective`
![image](https://user-images.githubusercontent.com/40422737/112982319-a53a1d00-915c-11eb-87a2-61df933d82b5.png)
`objective_pow`
![image](https://user-images.githubusercontent.com/40422737/112982442-cac72680-915c-11eb-9f7b-14a10d2b2f5c.png)

***Verifier - objective***
```c
system objective;
```
![image](https://user-images.githubusercontent.com/40422737/112982880-4c1eb900-915d-11eb-92dc-730bd7ac3852.png)

Pressed F5 to reload

***Verifier - objective_pow***
```c
system objective_pow;
```
![image](https://user-images.githubusercontent.com/40422737/112983215-b3d50400-915d-11eb-857d-9821ad91fe79.png)

**Expected behavior**
Expected for both to take similar time to be interchangeable when defining expressions

**Desktop**
 - OS: Ubuntu 20.04.2 LTS
 - UPPAAL 4.1.20-stratego-8-beta6 (rev. 2B32AEEE2ECD4B4F), January 2020

**Comment by mikucionisaau** [comment]
Yes, integer multiplication is much faster than `pow` which takes arbitrary floating point numbers, which is useful in the context of arbitrary powers, including roots. I do not think we can do much here, except perhaps some very smart static analysis, which is an overkill here.
Just like in programming: simply use the integer multiplication whenever you can.
