### ISSUE TITLE
OS Error on Linux/Mac OS if installation path includes spaces

### ISSUE THREAD

**Issue by mcje** [UPPAALModelChecker/UPPAAL-Meta#27]
**Describe the bug**
On Linux, if UPPAAL is installed in a path that includes spaces, it gives OS errors for the GUI and file not found errors for verifyta/server.

**To Reproduce**
Install UPPAAL on a path similar to:
> /home/user01/My Dir With Spaces/uppaal
open the GUI or execute verifyta / server directly

**Expected behavior**
It should just work

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 4.1.24 (also doesnt work on 4.0.13 but gives different errors)

**Additional context**
Example errors:
> ./server: line 10: /home/user01/My: No such file or directory
It just cuts off at the dir with spaces, so I am guessing the path string is not formatted correctly for Linux? I.e. not escaping spaces properly.

**Comment by yrke** [comment]
We have the same/similar issue confirmed for Mac OS

**Comment by mikucionisaau** [comment]
fxied and released `4.1.25-5`, also `main`
