### ISSUE TITLE
Division using only ints breaks stopwatch

### ISSUE THREAD

**Issue by koch10** [UPPAALModelChecker/UPPAAL-Meta#293]
**Describe the bug**
Whenever specifying the rate of a hybrid clock on location invariants using a division involving only integers, the hybrid clock will break and not progress.
[stopwatch_int_bug.zip](https://github.com/user-attachments/files/17266064/stopwatch_int_bug.zip)

**To Reproduce**
1. Open attached UPPAAL model.
2. Run the simulation queries.
3. Simulating x one can observe that x does not evolve, however, y evolves over time as expected.

**Expected behavior**
x should evolve like y.

**Version(s) of UPPAAL tested**
Bug observed in UPPAAL 5.0.0 and 5.1.0-beta5

**Desktop (please complete the following information):**
Windows 11

**Comment by mikucionisaau** [comment]
Expressions using integers correspond to integer operations and in particular `1/2` means integer division and evaluates to `0` (this is consistent with C/[C++](https://godbolt.org/z/x3bWYja85)/Java), so the expression `x' == 1/2` is equivalent to `x' == 0` which stops the clock `x` and thus its value stays at zero.

For floating point operations, please use floating point numbers or `double` variables (like `y' == 1/2.0` or `y' == 1.0/2`).
