### ISSUE TITLE
A transition that cannot be enabled is enabled and selected

### ISSUE THREAD

**Issue by eunkjee** [UPPAALModelChecker/UPPAAL-Meta#35]
[model_and_trace.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/6344114/model_and_trace.zip)

**Describe the bug**
-The transition that cannot be enabled (because the corresponding guard is false) is taken so that the corresponding syncronization and update are executed. 
-The enabled-taken transition is not displayed in red on the graphical representation in Simulator.

**To Reproduce**
1. Unzip the attached 'model_and_trace.zip' file
2. Open 'SCP_v7.01_3nodes_1quorum_3values(allnodes)_cnt8_gap1_thr100_v4.1.24.xml'
3. In Simulator, open 'SCP_v7.01_3nodes_1quorum_3values(allnodes)_cnt8_gap1_thr100_v4.1.24.xtr' trace file.
4. Proceed to the point where ballotStates[2].curState (in Global variables) becomes 1 from 0' in Simulation Trace. You can find that there are three enabled transitions - 'tickAdvance[0]: NodeTick -> NodeBallot(0)', 'tickAdvance[1]: NodeTick -> NodeNomination(1)', and 'nominationDone[2]: NodeBallot(2) -> NodeNomination(2)'.
5. By pressing Next button, you can see that 'tickAdvance[0]: NodeTick -> NodeBallot(0)' is taken.
6. By pressing Next button, you can see that 'tickAdvance[1]: NodeTick -> NodeNomination(1)' is taken.
7. By pressing Next button, you can find that 'tickAdvance[2]: NodeTick -> NodeNomination(2)' is taken although the guard 'canTick[2] && tickAllowed[2]' along with 'tickAdvance[2]!' is false; thus, cannot be enabled . Moreover, this taken transition is not displayed in red in NodeTick template.
 
**Expected behavior**
The only enabled transition 'nominationDone[2]: NodeBallot(2) -> NodeNomination(2)' should be taken. 

**Screenshots**
![CounterexampleTrace_1](https://user-images.githubusercontent.com/16930853/115404817-a4128200-a228-11eb-83fe-d44d7605aba2.png)
![CounterexampleTrace_2](https://user-images.githubusercontent.com/16930853/115404822-a543af00-a228-11eb-82ad-274d956bd7a2.png)
![CounterexampleTrace_3](https://user-images.githubusercontent.com/16930853/115404825-a5dc4580-a228-11eb-8009-7a0413de68fc.png)
![CounterexampleTrace_4](https://user-images.githubusercontent.com/16930853/115404827-a5dc4580-a228-11eb-9169-396193559b8e.png)
![CounterexampleTrace_5](https://user-images.githubusercontent.com/16930853/115404828-a674dc00-a228-11eb-9ba6-cc8b5ceb58f0.png)
![CounterexampleTrace_6](https://user-images.githubusercontent.com/16930853/115404830-a674dc00-a228-11eb-90a9-48f9821f5337.png)
![CounterexampleTrace_7](https://user-images.githubusercontent.com/16930853/115404831-a70d7280-a228-11eb-9854-35db6e9d391b.png)
![CounterexampleTrace_8](https://user-images.githubusercontent.com/16930853/115404834-a7a60900-a228-11eb-80aa-880c9cbdfbf0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Chromium
 - Version: 90.0.4430.72

**Comment by eunkjee** [comment]
We encountered this problem often when verifying our model, so the verification is no longer progressing. Could you please let us know if this is likely to be resolved in the near future?

**Comment by mikucionisaau** [comment]
I think it concerns only the symbolic simulator, i.e. the verifier is not taking the disabled transtitions.
The issue should be fixed in 4.1.26

**Comment by mikucionisaau** [comment]
I have checked the attached trace in 4.1.26 and it looks a bit different, it does not have the guard contradictions described.
![image](https://user-images.githubusercontent.com/4868894/150535881-b41f5b6f-7d19-4bb8-8e8f-8b3eab0bda56.png)
So I am closing the report, feel free to open if the issue persists.
Thanks for reporting!
