### ISSUE TITLE
Clock guards on broadcast receivers not handled correctly

### ISSUE THREAD

**Issue by GameMonkey** [UPPAALModelChecker/UPPAAL-Meta#37]
**Describe the bug**
Clock guards on broadcast receivers do not give an error or the "correct" transitions.

**To Reproduce**
[broadcastreceiverguard.xml.gz](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/8754791/broadcastreceiverguard.xml.gz)

Make two new templates (Sender and Receiver) and a global clock and a broadcast channel.
![image](https://user-images.githubusercontent.com/7374161/116875763-ba064680-ac1b-11eb-94c4-6d0dc006c5b5.png)

Have the Sender send within the interval [0, 3] and have Receiver can har guard for x == 1. Instantiate these two templates.
![image](https://user-images.githubusercontent.com/7374161/116876037-1f5a3780-ac1c-11eb-833f-1d8dc986f0b2.png)
![image](https://user-images.githubusercontent.com/7374161/116876088-313bda80-ac1c-11eb-99e1-84ebab0c7295.png)

**Expected behavior**
Either 
 - an error telling me that I cannot have clock guards on the edge with broadcast receive,
 - or enter the symbolic model checker tab and see 3 transitions.
     -   [0, 1) with no receivers.
     - [1, 1] with one receiver.
     - (1, 3] with no receivers.

Currently there are 2 identical transitions for [0,1), 1 transition for x = 1, and 1 deadlock state when x>1.

**Version(s) of UPPAAL tested**
I have tried with stratego-8-beta7.
```
Copyright (c) 1995 - 2021, Uppsala University and Aalborg University.
All rights reserved.
Compiled with g++-10 -Wall -Wempty-body -DNDEBUG -O3 -ffloat-store -fPIC -mtune=generc -DLIBXML_STATIC -DENABLE_TIGA -DMULTI_TERMINAL -DENABLE_TIGA_SMC -DENABLE_TIGA -DMUTI_TERMINAL -DENABLE_STORE_MINGRAPH -DTIGA_OTF_BUCHI -DENABLE_LSC -DENABLE_POLYHEDRA_HECKING  -DBOOST_DISABLE_THREADS -std=c++17
Free for academic and non-commercial use only.
```

**Desktop (please complete the following information):**
 - Version [see Help About menu, or `verifyta --version` e.g. 4.1.25]
 - Kubuntu 20.10, 64 bit

**Comment by GameMonkey** [comment]
This is the full output from verifyta:
```
(Academic) UPPAAL 4.1.20-stratego-8-beta7 (rev. A794F860A0933DC4), April 2021
Copyright (c) 1995 - 2021, Uppsala University and Aalborg University.
All rights reserved.
Compiled with g++-10 -Wall -Wempty-body -DNDEBUG -O3 -ffloat-store -fPIC -mtune=generc -DLIBXML_STATIC -DENABLE_TIGA -DMULTI_TERMINAL -DENABLE_TIGA_SMC -DENABLE_TIGA -DMUTI_TERMINAL -DENABLE_STORE_MINGRAPH -DTIGA_OTF_BUCHI -DENABLE_LSC -DENABLE_POLYHEDRA_HECKING  -DBOOST_DISABLE_THREADS -std=c++17
Free for academic and non-commercial use only.

```

**Comment by mikucionisaau** [comment]
We used to have an error reporting on the urgent receivers with clock guards, but something has changed here and the simulator is trying to generate exponentially many successors, which are also incorrect.

**Comment by mikucionisaau** [comment]
Interestingly, the symbolic queries yield an error (about broadcast receiver with clock guard), but the simbolic simulator is computing something.
SMC queries accept such models, and such behavior also needs investigation.

**Comment by mikucionisaau** [comment]
Pending release

**Comment by mikucionisaau** [comment]
Fix released with Stratego-10
![image](https://user-images.githubusercontent.com/4868894/194232270-7ee64a3b-66ad-4836-80ac-a8280055608b.png)
![image](https://user-images.githubusercontent.com/4868894/194232305-cd0ff603-9609-472f-a26a-90ace50faf38.png)
![image](https://user-images.githubusercontent.com/4868894/194232363-36b7d7b2-76fa-4cb2-9738-615afc7c9a43.png)
