### ISSUE TITLE
Transitions that are not in the Enabled Transitions are taken

### ISSUE THREAD

**Issue by eunkjee** [UPPAALModelChecker/UPPAAL-Meta#39]
**Describe the bug**
-Transitions that are not in the Enabled Transitions are taken in Simulator. 
-Although Enabled Transitions shows deadlock, many further steps can be added in the simulation trace.

**To Reproduce**
1.	Unzip the attached 'model_and_trace2.zip' file
[model_and_trace2.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/6559534/model_and_trace2.zip)
2.	Open 'SCP_v8.01_3nodes_1quorum_3values(allnodes)_cnt8_gap1_thr100_v4.1.24.xml'
3.	Go to Simulator, open the trace file ‘SCP_v8.01_3nodes_1quorum_3values(allnodes)_cnt8_gap1_thr100_v4.1.24.xtr'.
4.	Proceed to the point where ballotStates[2].curState (in Global variables) becomes 1 from 0' in Simulation Trace. You can find that there are three enabled transitions - 'NodeNomination(1)’,’NodeBallot(0)', and ‘nominationDone[2]: NodeBallot(2) → NodeNomination(2)’
5.	By pressing Next button, you can see that 'NodeNomination(1)' is taken.
6.	By pressing Next button, you can find that 'NodeNomination(2)' is taken and update is done although it is not in the Enabled Transition. Moreover, this taken transition is not displayed in red in NodeNomination(2) template. 
7.	By pressing Next button, ’NodeBallot(0)' in Enabled Transitions is taken.
8.	By pressing Next button, ’NodeNomination(0)' in Enabled Transitions is taken.
9.	By pressing Next button, ’NodeBallot(1)' in Enabled Transitions is taken.
10.	By pressing Next button, you can find that ‘nominationDone[2]: NodeBallot(2) → NodeNomination(2)’ in Enabled Transitions is not taken and another transition of NodeBallot(2) is taken which is enabled by the undesired execution described in Step 6. A This taken transition is not displayed in red in NodeBallot (2) template. 
11.	At the latter part of the trace, you can find ‘deadlock’. Although Enabled Transitions shows deadlock, many further steps can proceed in the simulation trace. Suddenly NodeSlot(0) moves from SlotStarted to SlotUnknown in the last step, although the guard is not true.

**Expected behavior**
-'NodeNomination(2)' shouldn’t be taken because it is not in the Enabled Transition.
-The only enabled transition 'nominationDone[2]: NodeBallot(2) -> NodeNomination(2)' should be taken.

**Version(s) of UPPAAL tested**
UPPAAL v4.1.24

**Screenshots**
![2021-05-28 (1)](https://user-images.githubusercontent.com/16930853/119956021-9ac0c600-bfdb-11eb-8dae-8b47a73b861c.png)
![2021-05-28 (2)](https://user-images.githubusercontent.com/16930853/119956019-9ac0c600-bfdb-11eb-80d6-a052072b2ab9.png)
![2021-05-28 (3)](https://user-images.githubusercontent.com/16930853/119956015-9a282f80-bfdb-11eb-95cf-dacf9677a964.png)
![2021-05-28 (4)](https://user-images.githubusercontent.com/16930853/119956012-9a282f80-bfdb-11eb-9269-a05d25cd1162.png)
![2021-05-28 (5)](https://user-images.githubusercontent.com/16930853/119956010-998f9900-bfdb-11eb-9605-d31685ac3787.png)
![2021-05-28 (6)](https://user-images.githubusercontent.com/16930853/119956008-998f9900-bfdb-11eb-98ec-e5cdf6e2784d.png)
![2021-05-28 (7)](https://user-images.githubusercontent.com/16930853/119956004-985e6c00-bfdb-11eb-8265-2ce4b841f101.png)
![2021-05-28 (8)](https://user-images.githubusercontent.com/16930853/119956053-a01e1080-bfdb-11eb-8f23-f3095556aa8d.png)
![2021-05-28 (9)](https://user-images.githubusercontent.com/16930853/119956051-9f857a00-bfdb-11eb-8ea1-4926cf86247a.png)
![2021-05-28 (10)](https://user-images.githubusercontent.com/16930853/119956049-9f857a00-bfdb-11eb-94d3-45bbb0958b55.png)
![2021-05-28 (11)](https://user-images.githubusercontent.com/16930853/119956047-9eece380-bfdb-11eb-906a-0f2980d08b9e.png)
![2021-05-28 (12)](https://user-images.githubusercontent.com/16930853/119956045-9eece380-bfdb-11eb-9473-092686564ffc.png)
![2021-05-28 (13)](https://user-images.githubusercontent.com/16930853/119956042-9e544d00-bfdb-11eb-802b-2d62f95af636.png)
![2021-05-28 (14)](https://user-images.githubusercontent.com/16930853/119956038-9dbbb680-bfdb-11eb-909f-70e79c645948.png)
![2021-05-28 (15)](https://user-images.githubusercontent.com/16930853/119956036-9dbbb680-bfdb-11eb-9cfe-50cc259b8705.png)
![2021-05-28 (16)](https://user-images.githubusercontent.com/16930853/119956035-9d232000-bfdb-11eb-9640-39e779bb1b0b.png)
![2021-05-28 (18)](https://user-images.githubusercontent.com/16930853/119956034-9d232000-bfdb-11eb-8503-bded14a083b7.png)
![2021-05-28 (19)](https://user-images.githubusercontent.com/16930853/119956033-9c8a8980-bfdb-11eb-8ba1-106c29d18019.png)
![2021-05-28 (20)](https://user-images.githubusercontent.com/16930853/119956030-9c8a8980-bfdb-11eb-8d8d-a9977bcffc2f.png)
![2021-05-28 (21)](https://user-images.githubusercontent.com/16930853/119956029-9bf1f300-bfdb-11eb-878b-b974dd3c4dc3.png)
![2021-05-28 (22)](https://user-images.githubusercontent.com/16930853/119956026-9bf1f300-bfdb-11eb-95b7-7735d36d95bf.png)
![2021-05-28 (23)](https://user-images.githubusercontent.com/16930853/119956025-9b595c80-bfdb-11eb-8f4e-6184e617236a.png)
![2021-05-28 (24)](https://user-images.githubusercontent.com/16930853/119956022-9b595c80-bfdb-11eb-976d-983e4582ca31.png)

**Desktop (please complete the following information):**
 - Version:  UPPAAL 4.1.24 
 - OS: Ubuntu 20.04.2 LTS

**Additional context**

**Comment by mikucionisaau** [comment]
I think it concerns only the symbolic simulator, i.e. the verifier is not taking the disabled transtitions.
The issue should be fixed in 4.1.26

**Comment by yrke** [comment]
Please feel free to reopen the issue if the error is still present in 4.1.26.
