### ISSUE TITLE
Probability Density Distribution graph cut's off the leftmost digit

### ISSUE THREAD

**Issue by GameMonkey** [UPPAALModelChecker/UPPAAL-Meta#40]
**Describe the bug**
Probability Density Distribution graph cut's off the leftmost digit.

**To Reproduce**

[Model: error_cut.tar.gz](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/6685861/error_cut.tar.gz)

1. Execute Uppaal-XML with set learning parameters _(Might not be important with these settings, but it gives a strategy faster)_:
   * Number of successful runs: 1000
   * Maximum number of runs: 1000
   * Number of good runs: 1000
   * Total maximum number of iterations: 1
   * m_option_imitation_iterations: 1
2. Execute the probability query.
3. On the second query, right-click and choose Probability Density Distribution. Here the leftmost digit is cut away.

**Expected behavior**
The leftmost bucket should start at 270, not just 70. Especially when the displayed samples are in [276.7, 1830]

**Version(s) of UPPAAL tested**
UPPAAL 4.1.20-stratego-8-beta7 (rev. A794F860A0933DC4)

**Screenshots**
![image](https://user-images.githubusercontent.com/7374161/122743077-ee46cc80-d286-11eb-8d5c-96efb3f819c4.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.10, Java openjdk 14.0.2 2020-07-14

**Comment by GameMonkey** [comment]
To clarify:
It is the leftmost digit on the x-axis. So instead of "70", it should say "270".

**Comment by mikucionisaau** [comment]
Fix released with Stratego-10
![image](https://user-images.githubusercontent.com/4868894/194232780-8dc4fa7e-df9a-4185-ac3e-467e75cbab34.png)
