### ISSUE TITLE
Learning Parameter Field throws exception on "wrong" formatting

### ISSUE THREAD

**Issue by GameMonkey** [UPPAALModelChecker/UPPAAL-Meta#41]
**Describe the bug**
The Learning Parameter fields throw exceptions if one changes values that include a comma.

**To Reproduce**
1. Go to Options -> Learning Parameters
2. Change the first parameter to 1000 and chose any other field. (The UI will change the value to "1,000" with a comma)
3. Now go back to the first parameter, click after the last digit and remove it.
4. The field now has the value "1,00", and an exception is thrown.

**Expected behavior**
Remove the comma to show the value "100".

**Version(s) of UPPAAL tested**
UPPAAL 4.1.20-stratego-8-beta7 (rev. A794F860A0933DC4)

**Screenshots**
![image](https://user-images.githubusercontent.com/7374161/122750631-0d495c80-d28f-11eb-89e8-a31498f29c40.png)

![image](https://user-images.githubusercontent.com/7374161/122750669-189c8800-d28f-11eb-8ebb-79c300fece3f.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.10, Java openjdk 14.0.2 2020-07-14

**Comment by yrke** [comment]
Issue is fixed in latest beta release, uppaal-4.1.20-stratego8-beta11
