### ISSUE TITLE
Lack of Broadcast-chan check for learning-methods

### ISSUE THREAD

**Issue by petergjoel** [UPPAALModelChecker/UPPAAL-Meta#43]
**Describe the bug**
The learning-methods of stratego rely on sampling a stochastic system.
Therefor all channels should be marked as broadcast to ensure independent progress, which is required for SMC.

**To Reproduce**
Attempt to valide the two propositions in the attached model: [robot3.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/6878442/robot3.zip).
The `simulate` query will fail with the correct error that "All channels must be broadcast", the following `minE` proposition computes a strategy but should terminate.

**Expected behavior**
The verification of the `minE` property should fail.

**Version(s) of UPPAAL tested**
- uppaal64-4.1.20-stratego-8-beta8
- newest nightly build: 3E4B8103E3C04E1D

**Desktop (please complete the following information):**
 - OS, Java version: Fedora 33.

**Comment by mikucionisaau** [comment]
Fix released with Stratego-10
![image](https://user-images.githubusercontent.com/4868894/194233144-838a365b-a2aa-4e93-a14c-b4fff2bf2d4f.png)
