### ISSUE TITLE
Stratego-8-beta-7: changing statistical options only take effect after reloading the model

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#44]
**Describe the bug**
I noticed today that changing the parameter *Discretization step for hybrid systems* only took effect after reloading the model with *Reload Simulator*. This feels counter-intuitive (at least it is not explained that you have to do this), but maybe necessary as the options are now saved in the model.

**To Reproduce**
I have created a MWE: [MWE_changeoptions.xml.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/6945926/MWE_changeoptions.xml.zip).
1. Open de MWE.
2. Go to *Verifier* tab, run the simulate query, and open the plot of the results. I should look like a smooth curve going from 40 to 0.
3. Go to *Options* -> *Statistical parameters*, change the value for *Discretization step for hybrid systems* to 1.0, and click OK to close the option window.
4. Run the simulate query again and open the plot of the results. The plot should look suspiciously the same.
5. Reload the model to the server by pressing F5 or going to *View* -> *Reload Simulator*.
6. Run the simulate query again and open the plot of the results. Now you see that curve no longer goes to 0 (it is flat around 18). 
7. (Optionally) Go to *Options* -> *Clear option overrides*. Now perform steps 4-6 again so see that the change only happens after reloading the model.

**Expected behavior**
After changing options for the queries, the changed options should have immediate effect when queries are run again. Maybe changing settings should automatically reload the simulator.

**Version(s) of UPPAAL tested**
UPPAAL Stratego 8 beta 7.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-8-beta7 (rev. A794F860A0933DC4), April 2021.
 - OS, Java version: Ubuntu 20.04.2 LTS

**Additional context**
Problem is also present if options are changed for queries individually with the clockwheel button.

**Comment by yrke** [comment]
This problem should be fixed in the latest UPPAAL stratego beta release. If not please feel free to reopen the issue.
