### ISSUE TITLE
About window refers to old bug tracking system

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#45]
**Describe the bug**
The *About* window refers users to the old [Bugzilla]( http://bugsy.grid.aau.dk/) issue tracking system.

**Expected behavior**
The *About* window should refer users to [Github](https://github.com/UPPAALModelChecker/UPPAAL-Meta/issues) for reporting issues.

**Version(s) of UPPAAL tested**
UPPAAL Stratego-8-beta-7

**Desktop:**
 - Version UPPAAL 4.1.20-stratego-8-beta7 (rev. A794F860A0933DC4), April 2021
 - OS, Java version: Ubuntu 20.04.2 LTS

**Comment by yrke** [comment]
Thanks for letting us know, this will be fixed in the next public release
