### ISSUE TITLE
Stratego-8-beta-7: Model is not properly reloaded to server when a change is detected

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#46]
**Describe the bug**
If a modeler changes the model in the Editor tab and subsequently wants to run an existing query, the GUI is detecting that the model in the Editor tab differs from the one currently in use by the server. It generates a pop-up window and asks the user whether it should upload the new model to the server. Answering with Yes generates an error (often I get "Parse error in message from server: Expected "START_OBJECT", got "EOF"", sometimes also "Positions must be monotonically increasing"; subsequent tries can also generate memory issue errors.) Manually reloading the model to the server does solve the problem. 

**To Reproduce**
The [MWE](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/6954392/MWE_changeoptions.xml.zip) from my previous bug report #44 can also be used here. I assume the problem can be reproduced with any model.
1. Open the MWE.
2. Go to the Verifier tab and run the simulate query (just to make sure the current model is properly uploaded to the server).
3. Go to the Editor tab and change something in the model. For example, the initial value of `w` can be changed from `40.0` to `50.0`.
4. Go back to the Verifier tab and try to run the query again.
5. Click Yes in the pop-up window on whether to upload the new model to the server.
6. Get the error.

To get the memory issues, continue with the following steps:
7. Click OK to close the error window.
8. Try to run the query again. Now you should get a "Stream closed" error.
9. Manually reload the model to the server.
10. Run the query again to observe now there is no problem.
11. Go to the Editor tab and change the model again. For example, change the initial value of `w` back to `40.0`.
12. Go to the Verifier tab and run the query.
13. The followin error message is displayed "<html>Memory exhausted. See <br>http://bugsy.grid.aau.dk/bugzilla3/show_bug.cgi?id=63 <br>for more information.</html>"

**Expected behavior**
When the user selects Yes to upload the modified model, there should be now errors (only in case the changes to the model justify returning an error to the user).

**Version(s) of UPPAAL tested**
Tested with Stratego 8 beta 7.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-8-beta7 (rev. A794F860A0933DC4), April 2021
 - OS, Java version: Ubuntu 20.04.2 LTS

**Comment by yrke** [comment]
Fixed in latest beta release, uppaal-4.1.20-stratego-8-beta11
