### ISSUE TITLE
Stratego-8-beta-7: The plot of if-else functions shows incorrect values

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#50]
**Describe the bug**
Consider a model with a user-defined function using if-else statements. Plotting this function with the simulate query results in an incorrect graph. In the simple MWE included below, the plotting functionality only shows the result of the first if-statement, without switching to the else statement at appropriate times.

**To Reproduce**
This [MWE](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/7000626/MWE_changemodel.xml.zip) can be used to illustrate the problem. It contains two user-defined functions were `w` is a clock going from 100 to 0 in 10 seconds:
```
double direct()
{
    return trunc(w);
}

double indirect()
{
    if (w <= 0) return 0;
    else return trunc(w);
}
```

1. Go to the Verifier tab.
2. Check the simulate query.
3. Open the graph.
4. See that the plot of *indirect()* is not the same as *direct()*.

You can also change the return value of the if statement in *indirect()* to other values, like 10, and see that the plot of this function changes to the value you just inserted.

**Expected behavior**
The plot should correctly follow the cases as defined in the if-else statements. So in the MWE, the plots of *direct()* and *indirect()* should be exactly the same for the time interval `[0,10]`.

**Version(s) of UPPAAL tested**
Tested with UPPAAL Stratego 8 beta 7.

**Desktop (please complete the following information):**
 - Version UPPAAL 4.1.20-stratego-8-beta7 (rev. A794F860A0933DC4), April 2021
 - OS, Java version: Ubuntu 20.04.2 LTS

**Comment by yrke** [comment]
Fixed in latest beta release uppaal-4.1.20-stratego8-beta11
