### ISSUE TITLE
An infinite loop is triggered if a 2D array value is out of bounds.

### ISSUE THREAD

**Issue by GameMonkey** [UPPAALModelChecker/UPPAAL-Meta#52]
**Describe the bug**
An infinite loop is triggered if a 2D array value is out of bounds.

**To Reproduce**
Model: [out_of_bounds_2d_array.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/7005503/out_of_bounds_2d_array.zip)

1. Open model `out_of_bounds_2d_array.xml.`
2. Go into the simulator tab.
3. Wait until the end of time.

**Expected behavior**
An error that the chosen value is out of bounds.

**Version(s) of UPPAAL tested**
uppaal64-4.1.20-stratego-8-beta7

**Desktop (please complete the following information):**
 - (Academic) UPPAAL 4.1.20-stratego-8-beta7 (rev. A794F860A0
933DC4), April 2021
 - Ubuntu 20.04.2 LTS, openjdk 11.0.11 2021-04-20

**Comment by yrke** [comment]
Issue is fixed in latest beta release, uppaal-4.1.20-stratego-8-beta11
