### ISSUE TITLE
Symbolic simulator crashes server when assigning variable out-or-range

### ISSUE THREAD

**Issue by GameMonkey** [UPPAALModelChecker/UPPAAL-Meta#53]
**Describe the bug**
Assigning an out-of-range value to typedef'ed valuetype gives an XML error in the GUI, but the verifier gives a correct answer.

In the simulator tab, the error `Expected field name "src", got "path"` is given.

**To Reproduce**
1.Get the model `out_ot_range_assignment.xml` from here:
[out_of_range_assignment.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/7030030/out_of_range_assignment.zip)
2. Go to the Simulator tab.
3. See error.

**Expected behavior**
The same error message as when the query in the Verifier tab is run.

**Notes** 
Error messages workes fine for Concrete Simulator & Verifier, 

**Version(s) of UPPAAL tested**
4.1.20-stratego-8-beta7, 4.1.20-stratego-8-beta8, 4.1.20-stratego-8-beta9, 4.1.20-stratego-8-beta11

**Desktop (please complete the following information):**
 - (Academic) UPPAAL 4.1.20-stratego-8-beta7 (rev. A794F860A0
933DC4), April 2021
 - Ubuntu 20.04.2 LTS, openjdk 11.0.11 2021-04-20

**Comment by mikucionisaau** [comment]
Fixed and released in Stratego 8
![image](https://user-images.githubusercontent.com/4868894/150532700-e4dcf6c8-ebb1-49d2-8c56-a8190027960b.png)
