### ISSUE TITLE
Cruise control example contains the deprecated model feature '__reset__'

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#56]
**Describe the bug**
The cruise control example contains the component `Monitor`, which contains a location named `__RESET__`. This model feature has been deprecated and is no longer supported. Since Stratego 8 beta 10, the user is warned about this (that's nice!). But we should make sure that the supplied examples work out of the box. 

**To Reproduce**
1. Open the cruise control example from the demo folder.
2. Go to verifier and observe the deprecation error.

**Expected behavior**
A model without the `__RESET__` feature, such that no deprecation error is generated.

**Version(s) of UPPAAL tested**
Uppaal Stratego 8 beta 10 and beta 11.

**Desktop (please complete the following information):**
- Version UPPAAL 4.1.20-stratego-8-beta11 (rev. D1ACD86A2525A3DE), October 2021
- OS, Java version: Ubuntu 20.04.2 LTS

**Additional context**
Maybe also check other examples in the demo folder to ensure that they work with the released version.

**Comment by mikucionisaau** [comment]
Fixed and released in Stratego 8
![image](https://user-images.githubusercontent.com/4868894/150532418-cdc92e4d-8eb5-4cd0-8ba7-f10f49f57c5d.png)
