### ISSUE TITLE
Clock variables not initialized to zero in Simulator

### ISSUE THREAD

**Issue by LauraPanizo** [UPPAALModelChecker/UPPAAL-Meta#58]
**Describe the bug**
In the semantics of TA described in [1], clock variables are set to zero in the initial state. However, we have found two simple examples that show how the simulator does not follow this initialization.

[1] https://www.uppaal.com/uppaal-tutorial.pdf

**To Reproduce**
We provide two models of that show the bug.
First model (transition with guard)
1. Open the model.
2. Click on Simulator
3. See a loop-transition from the initial state that is enabled because clock x can be >20.However, initial state invariant is x<=10.

Second model (transition without guard)
1. Open the model.
2. Click on Simulator
3. See a deadlock because clock x can be >10  initially.

**Expected behavior**
In the first model, the simulator should not enable the transition, and only deadlock behavior is simulated.
In the second model, the deadlock behavior should not appear. In fact, when the second model is verified against not deadlock property (A [] ! deadlock) the property is satisfied.

**Version(s) of UPPAAL tested**
4.1.24 

**Screenshots**
First model error:
<img width="756" alt="first_model" src="https://user-images.githubusercontent.com/26867710/141453896-eeae52e8-187a-4ff1-a3d1-98c383348587.png">

Second model error:

<img width="824" alt="second_model" src="https://user-images.githubusercontent.com/26867710/141453946-4a45a92d-8f2f-426b-9873-0b692642c724.png">

**Desktop (please complete the following information):**
 - Version verifyta  4.1.23
 - OS Big Surf / Catalina , Java version: Java 11 openJDK

**Additional context**

**Comment by mikucionisaau** [comment]
Fixed in 4.1.26, also Stratego 8
![image](https://user-images.githubusercontent.com/4868894/150531624-240f1c8d-d3d4-4006-909c-ce984d8ea2c5.png)
