### ISSUE TITLE
No About item in Help menu under macOS

### ISSUE THREAD

**Issue by pacalet** [UPPAALModelChecker/UPPAAL-Meta#68]
**Describe the bug**
Under macOS there is no "_About_" item in the "_Help_" menu of the GUI. And the "_About Main_" item of the "_Main_" menu opens a pop-up that only says "_java version 1.0 (1.0)_", not the UPPAAL version.

**To Reproduce**
1. Launch the GUI
2. Click on "_Help_"
3. See that there is no "_About_" item
4. Click on the "_Main_" menu, select "_About Main_"
5. See that it only says "_java version 1.0 (1.0)_"

**Expected behavior**
There should be an easy way to find the UPPAAL version from the GUI under macOS, either in the "_Help_" menu or in the "_Main_" menu (which, by the way, should probably be named "_Uppaal_", instead of "_Main_").

**Version(s) of UPPAAL tested**
(Academic) UPPAAL 4.1.23 (rev. 6954DD724AC60A79), November 2019

**Screenshots**
<img width="800" alt="Screenshot1" src="https://user-images.githubusercontent.com/45038397/150824211-8b7da12c-f816-43eb-bbb4-70420a33dda5.png">
<img width="807" alt="Screenshot2" src="https://user-images.githubusercontent.com/45038397/150824237-51f4d252-69de-4adf-8eef-d28f53a61e7e.png">
<img width="282" alt="Screenshot3" src="https://user-images.githubusercontent.com/45038397/150824257-94ff8de9-a0a6-4b32-aea9-6b658d196b3e.png">

**Desktop (please complete the following information):**
 - Version (Academic) UPPAAL 4.1.23 (rev. 6954DD724AC60A79), November 2019
 - macOS 12.1, Monterey, Java version 14.0.1 2020-04-14

**Comment by yrke** [comment]
Thanks for your report. UPPAAL Version 4.1 (and earlier) does not provide native mac os integration, nor do we currently plan to provide this.  
For better Mac OS integration, including app bundles releases, we suggest using Uppaal Stratego 9, available from https://uppaal.org/downloads/ (Select tab stratego).

**Comment by pacalet** [comment]
Thanks. May I suggest that the official web site mentions this? Anyway, I just downloaded Uppaal Stratego 9 ((Academic) UPPAAL 4.1.26 (rev. 5C9F29B1BE2251E3), December 2021) and it has the very same issues. No way to get the version form the GUI. Shall I open a new issue?

**Comment by yrke** [comment]
Hi,  the latest version of stratego is 4.1.20-stratego-9, based on the version number I think you have downloaded the classical version of uppaal, here is a direct download link for stratego: https://uppaal.org/downloads/other/#uppaal-stratego

**Comment by pacalet** [comment]
Thanks. On the [downloads page](https://uppaal.org/downloads/) there are 2 links for macOS Uppaal Stratego 9. The first one I tested was [64-bit MacOS APP, version 4.1.20-stratego-9](https://www.it.uu.se/research/group/darts/uppaal/download/registration.php?id=12&subid=20). But apparently the `uppaal64-4.1.26-mac.zip` downloaded archive is the one for the classical version. This is maybe an error on the web page? I just tested the other one ([64-bit MacOS, version 4.1.20-stratego-9](https://www.it.uu.se/research/group/darts/uppaal/download/registration.php?id=12&subid=21)) and it looks correct. It downloads `uppaal-4.1.20-stratego-9-macos64.zip`, which has the correct _Help_ and _UPPAAL_ menus.

**Comment by mikucionisaau** [comment]
> Thanks. On the [downloads page](https://uppaal.org/downloads/) there are 2 links for macOS Uppaal Stratego 9. The first one I tested was [64-bit MacOS APP, version 4.1.20-stratego-9](https://www.it.uu.se/research/group/darts/uppaal/download/registration.php?id=12&subid=20). But apparently the `uppaal64-4.1.26-mac.zip` downloaded archive is the one for the classical version. This is maybe an error on the web page? I just tested the other one ([64-bit MacOS, version 4.1.20-stratego-9](https://www.it.uu.se/research/group/darts/uppaal/download/registration.php?id=12&subid=21)) and it looks correct. It downloads `uppaal-4.1.20-stratego-9-macos64.zip`, which has the correct _Help_ and _UPPAAL_ menus.

Sorry, I messed up the APP download links (I got an empty file on the APP links).
Now I fixed them. @pacalet  could you please try downloading it again?

**Comment by mikucionisaau** [comment]
We have two variants for MacOS for now: the archive (*-macos64.zip) and the app (*-app.zip).
The macos64 variant has very similar structure to other distributions, but it is very tedious to start it (one has to remove the quarantine attribute from many files), whereas the app variant fixes by itself once it is started (right-click and choose Open).

**Comment by pacalet** [comment]
I just tested both and they are fine. Thanks.
