### ISSUE TITLE
Download location of Uppaal Stratego 9 is unclear on Uppaal Stratego website

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#69]
The latest version of Uppaal Stratego (version 9) can be downloaded from [uppaal.org](https://uppaal.org/downloads/), which is different from the [Uppaal Stratego website](https://people.cs.aau.dk/~marius/stratego/) where users previously downloaded Uppaal Stratego (versions 7 and lower).

It would be nice if the Uppaal Stratego website redirect the users to the new download location, or have the downloads also on the Uppaal Stratego website. Also, keep in mind that if I Google for Uppaal Stratego, the first hit is the Uppaal Stratego website.

**Comment by mikucionisaau** [comment]
Fixed by adding links and disclaimer on ~marius/stratego page
