### ISSUE TITLE
Cannot insert new template by right clicking Project after clicking System declarations

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#73]
**Describe the bug**
The `Insert template` option is unable to be clicked with a right click on `Project` once you have selected the `System declarations` as the last selected element.

Normally you can add a new template by right clicking `Project`, `Declarations`, or any template you have, and then selecting `Insert template`. This is no longer possible once you selected `System declarations` first and then do the right click on `Project`. 

**To Reproduce**
1. Create a new model.
2. Right click `Project` and observe that `Insert template` is clickable.
3. Left click `System declarations`.
4. Right click `Project` and observe that `Insert template` is no longer clickable.
5. Left click `Declarations` or another template.
6. Right click `Project` and observe that `Insert template` is clickable again.

**Expected behavior**
You should always be able to insert a new template if you right click `Project`.

**Version(s) of UPPAAL tested**
Uppaal Stratego 9.

**Desktop (please complete the following information):**
- Version UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022
- OS, Java version: Ubuntu 20.04.3 LTS

**Comment by magoorden** [comment]
Maybe related to #72?

**Comment by mikucionisaau** [comment]
Fix released with Stratego-10
