### ISSUE TITLE
Incorrect location given when template has invalid initialization

### ISSUE THREAD

**Issue by GameMonkey** [UPPAALModelChecker/UPPAAL-Meta#76]
**Describe the bug**
When an invalid initialization is done in a template, the error message points to the global declarations.

**To Reproduce**
1. Open the attached model that shows the minimum example:
[wrong_location_for_error.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/8109036/wrong_location_for_error.zip)

**Expected behavior**
An error message that is pointing to the line in the given template's declarations.

**Version(s) of UPPAAL tested**
UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED)

**Desktop (please complete the following information):**
- Ubuntu 20.10, Java openjdk 14.0.2 2020-07-14

**Comment by mikucionisaau** [comment]
Fix released with Stratego-10
![image](https://user-images.githubusercontent.com/4868894/194235063-9067cc7b-e5da-4420-b92d-1a3f30391990.png)
