### ISSUE TITLE
Search / replace functionality in the GUI

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#79]
**Is your feature request related to a problem? Please describe.**
Currently, the Uppaal GUI does not support text-based search and replacement functionality. Having this functionality could resolve some inconveniences, like, e.g., renaming variables.

**Describe the solution you'd like**
The search and replacement functionality (shortcut ctrl+f) should allow user to search in the model based on a supplied search string and, possibly, replace it by the replacement string. It should be similar to search and replacement functionalities in other editors.

**Describe alternatives you've considered**
Right now, I can change the name of the variable I want to search for and use Check Syntax (F7) to indicate roughly where the model is broken.

**Comment by yrke** [comment]
This is something that we hope soon to be able to add to UPPAAL.

**Comment by thorulf4** [comment]
This was added in the latest beta release, however more find / replace functionality is underway
