### ISSUE TITLE
Clock weights on branching edges no evaluated correctly.

### ISSUE THREAD

**Issue by petergjoel** [UPPAALModelChecker/UPPAAL-Meta#8]
The attached model (`clock_prob_weight.xml`) reports that the sum of probabilities are `<=0` which is wrong.
The expected outcome should be as in `clock_prob_weight_fint.xml`, specifically:

`Pr[<=100] (<> Process.LX)` is 2/3 and
`Pr[<=100] (<> Process.LX)` is 1/3

![clock_prob_weight.xml](https://user-images.githubusercontent.com/1324691/102471156-23aefb00-4055-11eb-9476-f14a20a8526e.png)
![clock_prob_weight_fint.xml](https://user-images.githubusercontent.com/1324691/102471279-52c56c80-4055-11eb-899f-fb81f91630db.png)

[clock_prob_weight_models.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/5708409/clock_prob_weight.zip)

**Comment by mikucionisaau** [comment]
This is still an issue in Stratego 10 beta 6

**Comment by mikucionisaau** [comment]
Released with Stratego-10
![image](https://user-images.githubusercontent.com/4868894/194225401-17c8593f-cb9a-4bfb-8e65-55f600d2612a.png)
![image](https://user-images.githubusercontent.com/4868894/194225507-ddf31096-0d0e-4490-8fe8-15cb4302e7f7.png)
