### ISSUE TITLE
Safety synthesis is broken in Uppaal Stratego 9 using broadcast

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#84]
**Describe the bug**
Safety synthesis (i.e., the TIGA stuff) is broken in Uppaal Stratego 9, while it works in Uppaal Stratego 7. I used the train gate example to synthesize a safe strategy (`strategy Safe = control : A[] forall (i : id_t) forall (j : id_t) Train(i).Cross & Train(j).Cross imply i == j`), and subsequently I verified the safety property for the system under this strategy (`A[] forall (i : id_t) forall (j : id_t) Train(i).Cross & Train(j).Cross imply i == j under Safe`). Uppaal Stratego 9 comes to the conclusion that this query is not satisfied, which should not be the case for a synthesized strategy.

Furthermore, I noticed that the time duration of synthesis is significantly different between Uppaal Strategy 7 and 9. With Uppaal Stratego 9 it takes about 8.3 seconds, while on 7 it takes about 0.2 seconds (on the same virtual Ubuntu). Also memory wise there is a difference noticable: for version 9 resident/virtual memory usage peaks: 227,092KB / 264,780KB; for version 7 resident/virtual memory usage peaks: 36,488KB / 78,096KB.

**To Reproduce**
1. Open `train_gate.xml` from the demo folder with Uppaal Stratego 7 / 9.
2. Go to verification tab.
3. Add and run the queries
   - `strategy Safe = control : A[] forall (i : id_t) forall (j : id_t) Train(i).Cross & Train(j).Cross imply i == j`
   - `A[] forall (i : id_t) forall (j : id_t) Train(i).Cross & Train(j).Cross imply i == j under Safe`
5. Observe that the second query is satisfied in Uppaal Stratego 7, but not in Uppaal Stratego 9.

**Expected behavior**
Uppaal Stratego 9 should synthesize correct safe control strategies such that verifying the safety property under the synthesized strategy is succesfull. 

**Version(s) of UPPAAL tested**
Uppaal Stratego 7 and 9.

**Desktop (please complete the following information):**
 - Version: 
   - *Version 7*: UPPAAL 4.1.20-stratego-7 (rev. 12D93ED5FE521036), December 2019
   - *Version 9*: UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022
 - OS: Ubuntu 20.04.3 LTS, running as a virtual machine with VirtualBox 6.1.32 on MacOS 12.2.1
 - Java version: openjdk version "11.0.13" 2021-10-19, OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04), OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing).

**Comment by magoorden** [comment]
More info for reproducability of the bug.

Go to the `Editor` -> `Declarations`.

- If you have `chan        appr[N], stop[N], leave[N];`, synthesis is working fine and the synthesized strategy is verified to be correct.
- If you have `broadcast chan        appr[N], stop[N], leave[N];`, synthesis takes longer and more memory, and the synthesized strategy is no longer verified to be correct.

**Comment by mikucionisaau** [comment]
I tried the queries on both `train-gate.xml`, edited `train-gate.xml` with broadcast, and `train-gate-stat.xml`, all of them work correctly in Stratego-10.
![image](https://user-images.githubusercontent.com/4868894/194236258-614e57e4-b810-4c4e-b7a8-c5e70de6a925.png)
