### ISSUE TITLE
The copyright symbol is shown instead of the state name Occ in the symbolic simulator

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#85]
**Describe the bug**
The train gate example contains the component Gate that has the state `Occ`. Using the symbolic simulator, the state name is sometimes displayed as the copyright symbol ©️.

**To Reproduce**
1. Open `train-gate.xml` from the demo folder.
2. Go to the symbolic simulator tab.
3. Execute several `appr[i]: Train(i) -> Gate[i]` transitions, where `i` is a number between 0 and 5.
4. Observe in the simulation trace that the last element in the state tuple is sometimes ©️. 

**Expected behavior**
The simulation trace should show the true state name `Occ`.

**Version(s) of UPPAAL tested**
UPPAAL Stratego 9.

**Screenshots**
![Screenshot 2022-03-04 at 11 09 56](https://user-images.githubusercontent.com/36483423/156744948-a8dfa40c-a07a-4ea5-a64b-83d386211e9b.png)

**Desktop (please complete the following information):**
- Version: UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022
- OS: Ubuntu 20.04.3 LTS, running as a virtual machine with VirtualBox 6.1.32 on MacOS 12.2.1
- Java version: openjdk version "11.0.13" 2021-10-19, OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04), OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing).

**Additional context**

**Comment by yrke** [comment]
If i read the model correctly `Occ` and `(c)` are two different locations. 

![image](https://user-images.githubusercontent.com/1086483/156983630-1b90bb0e-a2ec-4ac8-b43c-0d3ab68cc5ae.png)

UPPAAL Stratego will now use the symbol `(c)` for an unnamed committed location. 

Please let me know if I missed something by reopening the issue.

**Comment by magoorden** [comment]
Well spotted! I haven't thought about. 
Nonetheless, is this usage of the `(c)` for unnamed comitted locations mentioned in the documentation? I can't find it.
