### ISSUE TITLE
Not all unaccepted clock expressions are captured with the syntax check

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#88]
**Describe the bug**
For both location invariants and guards, the expressions "must be a conjunction of simple conditions on clocks, differences between clocks, and boolean expressions not involving clocks. The bound must be given by an integer expression." (from the [documentation](https://docs.uppaal.org/language-reference/system-description/templates/locations/#invariants)). The syntax checker is not checking this in all parts of the model.

**To Reproduce**

1. Create a new model. 
2. Add to the declarations:
    ```
    clock timer = 1.0;
    double tau = 1.0;
    ```
3. Create the following three automata in the `Template`:
    ![Screenshot 2022-03-15 at 16 48 15](https://user-images.githubusercontent.com/36483423/158419030-66c88165-09c3-4b5d-aa22-02ce947a678b.png)
4. Check the syntax (F7 or `Tools` -> `Check Syntax`).
5. Observe that the invariant `timer <= tau` in the top left location is marked as problematic.
6. Change the initial location to the middle left location (thus 'fixing' the indicated syntax error).
7. Check the syntax (F7 or `Tools` -> `Check Syntax`).
8. Observe that the invariant `timer <= 1` is fine, and that the guard `timer >= tau` nor the invariant `timer <= tau` in the middle right location are marked as problematic.
9. Go to the concrete simulator tab and observe that no transition is possible.
10. Go back to the editor and change the initial location to the bottom left one (thus 'fixing' the guard syntax error).
11. Check the syntax (F7 or `Tools` -> `Check Syntax`). No error indicated.
12. Go to the concrete simulator tab and observe that you can do the first transition exactly at time 1.

**Expected behavior**
All syntax errors related to guards and invariants should be indicated to the user.  

**Version(s) of UPPAAL tested**
UPPAAL Stratego 9.

**Desktop (please complete the following information):**
- Version: UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022
- OS: Ubuntu 20.04.3 LTS, running as a virtual machine with VirtualBox 6.1.32 on MacOS 12.2.1
- Java version: openjdk version "11.0.13" 2021-10-19, OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04), OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing).

**Comment by RasmusRendal** [comment]
Thanks for bringing this to our attention. This issue has been supplanted by https://github.com/UPPAALModelChecker/utap/issues/11
