### ISSUE TITLE
error notice popup doesn't disappear

### ISSUE THREAD

**Issue by EstherHKim** [UPPAALModelChecker/UPPAAL-Meta#90]
**Describe the bug**
When I got error notice popup, it should be gone when I click [OK] or [x]. But it doesn't dissapear. Therefore I have to close the program using window task manager and sometimes I should reboot the system. When I tried same model on beta 8 rc2, it works well (same error pop up and when I click [x], it has disappeared :)

**To Reproduce**

**Expected behavior**
What I expect is, when I click error notice popup, I hope it gone therefore I can keep working on model without exit the program.**  

**Version(s) of UPPAAL tested**
Version: Stratego-10 beta1

**Screenshots**

**Desktop (please complete the following information):**
 - Version: Stratego-10 beta1
 - OS, Java version: Windows 10 64bit, Java 11.0.2

**Additional context**

**Comment by yrke** [comment]
Could you please includes the steps you took in order to get the error menu you can't close. 
Image attached: 
https://user-images.githubusercontent.com/89918210/159676075-93806dbc-c684-441a-ab59-dd69fcc47198.png

**Comment by EstherHKim** [comment]
I opened the model > choose concrete simulation > click [random]. 
and then, the error happened.

**Comment by yrke** [comment]
I managed to reproduce using random simulation. Hitting an error will not stop random simulation, so when the dialog is closed it will hit the error again. 
[hit-error-random.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/8332317/hit-error-random.zip)

**Comment by yrke** [comment]
This issue will be fixed in the next beta release of uppaal

**Comment by mikucionisaau** [comment]
The fix is released with Stratego-10
