### ISSUE TITLE
software froze and not working (even closing the window is not available)

### ISSUE THREAD

**Issue by EstherHKim** [UPPAALModelChecker/UPPAAL-Meta#91]
**Describe the bug**
When I use [concrete simulation] with [Random] function,
 suddenly the program stopped and just froze. Nothing is working even I can not close the window. I need to go to window task manager and force to close it. 

**To Reproduce**
1. Go to 'concrete simulation'
2. Click on 'Random'
4. See error: No error, just stopped. 

**Expected behavior**
I expecting if there is error with my model, I want to see error notification and want to fix it. But it just stopped and I don't know what I should do. 

**Version(s) of UPPAAL tested**
uppaal-4.1.20-stratego-9-win64

**Screenshots**
![win9_error](https://user-images.githubusercontent.com/89918210/159901646-4fa475b0-8ee5-47ea-97a7-1ef7f60c88f6.png)

**Desktop (please complete the following information):**
 - Version [uppaal-4.1.20-stratego-9-win64]
 - OS, Java version: [e.g. Windows 10 64bit, Java 11]

**Additional context**
Thank you for your help in advance, and let me know if there is more information is needed. :)

**Comment by mikucionisaau** [comment]
In Stratego-10 the async interaction with engine has been significantly improved, so hopefully this does not happen again.
