### ISSUE TITLE
Supremum giving incorrect result when clock copying is used.

### ISSUE THREAD

**Issue by GameMonkey** [UPPAALModelChecker/UPPAAL-Meta#93]
**Describe the bug**
Uppaal gives incorrect results in supremum queries of clocks, where clock copying is part of the model.

In the attached model of a small sporadic scheduling system, I have a queue of the task activations as they arrive. When the queue is popped, I copy the clocks on step further in the queue.

Now, having a query on the form _sup{eventQueue.Measure}: queue[0]_, where check the maximum age of the clock. I know this query should be "<=12" in the given system, but Uppaal tells me it is "< inf".

The clock copying is in the template _eventQueue_ in the function _popQueue()_. If I comment those three lines, the result is indeed "<=12".

**To Reproduce**
1. Open the model: [supremum.zip](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/8342264/supremum.zip)
2. Run it with verifyta without any options.
3. The query return "<inf".
4. Now comment the clock copying in _popQueue_ in _eventQueue_.
5. Run verifyta again and see the result become "<=12".

**Expected behavior**
I would expect that the query returned "<=12" in the first case.

**Version(s) of UPPAAL tested**
UPPAAL 4.1.26-1

**Desktop (please complete the following information):**
- (Academic) UPPAAL 4.1.26-1 (rev. 7BCF30B7363A9518), February 2022
- 20.04.1-Ubuntu, openjdk 11.0.14 2022-01-18

**Additional context**
This bug might be related to bug #92.

**Comment by RasmusRendal** [comment]
This is an issue with extrapolation, which seems to be turned on for models where it shouldn't, specifically models with clock coping. We will fix this, but until then, you can use the workaround of setting Extrapolation to None in the engine options menu.

**Comment by mikucionisaau** [comment]
The fix has been released with Stratego-10
