### ISSUE TITLE
[stratego] Queries with timelock errors still produce a green light

### ISSUE THREAD

**Issue by EstherHKim** [UPPAALModelChecker/UPPAAL-Meta#94]
**Describe the bug**
I tried opt strategy using verification function. It get green light but no diagram or other result. Maybe it is my model issue though. 

**To Reproduce**
1. Go to 'Verifier'
2. Click on 'input query and [check]'

**Expected behavior**
I am expecting the result of verification be shown. 

**Version(s) of UPPAAL tested**
UPPAAL 4.1.20-stratego-9  / windows version

**Screenshots**
![uppaal_pond_verification_error_01](https://user-images.githubusercontent.com/89918210/159999655-cb0e61b0-2029-4c2d-9299-256ab864a88a.png)
![uppaal_pond_verification_error_02](https://user-images.githubusercontent.com/89918210/159999704-8a53d9b3-9ede-4a43-bc67-2076eaeabe9e.png)

**Desktop (please complete the following information):**
 - Version [UPPAAL 4.1.20-stratego-9]
 - OS, Java version: [Windows 10 64bit, Java 11]

**Additional context**
MWE for the error: [timelockerror.xml.gz](https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/8752632/timelockerror.xml.gz)

**Comment by RasmusRendal** [comment]
Would you attach the model you are using to get this result?

**Comment by mikucionisaau** [comment]
Fixed released with Stratego-10.
