### ISSUE TITLE
cannot run program / error=2, No such file or directory

### ISSUE THREAD

**Issue by EstherHKim** [UPPAALModelChecker/UPPAAL-Meta#98]
**Describe the bug**
I cannot use simulation from first phase, and when I reload engine, the error message popup. 

**To Reproduce**
1. Go to 'Engine'
2. Click on Reload Englid 
4. See error "error=2, No such file or directory"

**Expected behavior**
Concreate simulation works

**Version(s) of UPPAAL tested**
A list of UPPAAL versions where the behaviour is observed, and optionally a version where it works as expected. 

**Screenshots**
![US_ver 9_error](https://user-images.githubusercontent.com/89918210/162171470-98be082b-ad0c-4091-be4d-f10e5c3c2a31.png)

**Desktop (please complete the following information):**
 - Version [UPPAAL 4.1.20-stratego-9]
 - OS, Java version: [Ubuntu 20.04.3 LTS / main is windows and I am using Linux with VMware ]

**Additional context**
Is it could be my model problem or laptop problem.. ?

**Comment by mikucionisaau** [comment]
My guess is that there was some kind of `libc` version conflict, which has been addressed with more robust checking of the server binary.

The fix released with Stratego-10.
